/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountsDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.AccountsRecord, com.petpace.db.jooq.tables.pojos.Accounts, java.lang.Integer> {

	/**
	 * Create a new AccountsDao without any configuration
	 */
	public AccountsDao() {
		super(com.petpace.db.jooq.tables.Accounts.ACCOUNTS, com.petpace.db.jooq.tables.pojos.Accounts.class);
	}

	/**
	 * Create a new AccountsDao with an attached configuration
	 */
	public AccountsDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Accounts.ACCOUNTS, com.petpace.db.jooq.tables.pojos.Accounts.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.Accounts object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Accounts fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.ID, value);
	}

	/**
	 * Fetch records that have <code>fullname IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByFullname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.FULLNAME, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByEmail(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.EMAIL, values);
	}

	/**
	 * Fetch a unique record that has <code>email = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Accounts fetchOneByEmail(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.EMAIL, value);
	}

	/**
	 * Fetch records that have <code>imageUrl IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByImageurl(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.IMAGEURL, values);
	}

	/**
	 * Fetch records that have <code>passToken IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByPasstoken(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.PASSTOKEN, values);
	}

	/**
	 * Fetch records that have <code>password IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByPassword(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.PASSWORD, values);
	}

	/**
	 * Fetch records that have <code>salt IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchBySalt(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.SALT, values);
	}

	/**
	 * Fetch records that have <code>lastLogin IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByLastlogin(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.LASTLOGIN, values);
	}

	/**
	 * Fetch records that have <code>dateCreated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByDatecreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.DATECREATED, values);
	}

	/**
	 * Fetch records that have <code>dateUpdated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByDateupdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.DATEUPDATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Accounts> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Accounts.ACCOUNTS.STATUS, values);
	}
}
