/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertsDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.AlertsRecord, com.petpace.db.jooq.tables.pojos.Alerts, java.lang.Integer> {

	/**
	 * Create a new AlertsDao without any configuration
	 */
	public AlertsDao() {
		super(com.petpace.db.jooq.tables.Alerts.ALERTS, com.petpace.db.jooq.tables.pojos.Alerts.class);
	}

	/**
	 * Create a new AlertsDao with an attached configuration
	 */
	public AlertsDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Alerts.ALERTS, com.petpace.db.jooq.tables.pojos.Alerts.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.Alerts object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Alerts fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Alerts.ALERTS.ID, value);
	}

	/**
	 * Fetch records that have <code>rule_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByRuleId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.RULE_ID, values);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>sensor_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchBySensorId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.SENSOR_ID, values);
	}

	/**
	 * Fetch records that have <code>message IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByMessage(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.MESSAGE, values);
	}

	/**
	 * Fetch records that have <code>data IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByData(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.DATA, values);
	}

	/**
	 * Fetch records that have <code>processed IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByProcessed(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.PROCESSED, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Alerts> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Alerts.ALERTS.CREATED, values);
	}
}
