/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationsDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.AlertNotificationsRecord, com.petpace.db.jooq.tables.pojos.AlertNotifications, java.lang.Integer> {

	/**
	 * Create a new AlertNotificationsDao without any configuration
	 */
	public AlertNotificationsDao() {
		super(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS, com.petpace.db.jooq.tables.pojos.AlertNotifications.class);
	}

	/**
	 * Create a new AlertNotificationsDao with an attached configuration
	 */
	public AlertNotificationsDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS, com.petpace.db.jooq.tables.pojos.AlertNotifications.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.AlertNotifications object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.AlertNotifications> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.AlertNotifications fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>alert_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.AlertNotifications> fetchByAlertId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.ALERT_ID, values);
	}

	/**
	 * Fetch records that have <code>confirmationRequired IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.AlertNotifications> fetchByConfirmationrequired(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.CONFIRMATIONREQUIRED, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.AlertNotifications> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.CREATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.AlertNotifications> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.AlertNotifications.ALERT_NOTIFICATIONS.STATUS, values);
	}
}
