/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedsDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.BreedsRecord, com.petpace.db.jooq.tables.pojos.Breeds, java.lang.String> {

	/**
	 * Create a new BreedsDao without any configuration
	 */
	public BreedsDao() {
		super(com.petpace.db.jooq.tables.Breeds.BREEDS, com.petpace.db.jooq.tables.pojos.Breeds.class);
	}

	/**
	 * Create a new BreedsDao with an attached configuration
	 */
	public BreedsDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Breeds.BREEDS, com.petpace.db.jooq.tables.pojos.Breeds.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(com.petpace.db.jooq.tables.pojos.Breeds object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Breeds> fetchById(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Breeds.BREEDS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Breeds fetchOneById(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.Breeds.BREEDS.ID, value);
	}

	/**
	 * Fetch records that have <code>uid IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Breeds> fetchByUid(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Breeds.BREEDS.UID, values);
	}

	/**
	 * Fetch a unique record that has <code>uid = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Breeds fetchOneByUid(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.Breeds.BREEDS.UID, value);
	}
}
