/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessesDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.BusinessesRecord, com.petpace.db.jooq.tables.pojos.Businesses, java.lang.Integer> {

	/**
	 * Create a new BusinessesDao without any configuration
	 */
	public BusinessesDao() {
		super(com.petpace.db.jooq.tables.Businesses.BUSINESSES, com.petpace.db.jooq.tables.pojos.Businesses.class);
	}

	/**
	 * Create a new BusinessesDao with an attached configuration
	 */
	public BusinessesDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Businesses.BUSINESSES, com.petpace.db.jooq.tables.pojos.Businesses.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.Businesses object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Businesses fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Businesses.BUSINESSES.ID, value);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByAddressId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.ADDRESS_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>address_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Businesses fetchOneByAddressId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Businesses.BUSINESSES.ADDRESS_ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByName(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>name = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Businesses fetchOneByName(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.Businesses.BUSINESSES.NAME, value);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByUrl(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.URL, values);
	}

	/**
	 * Fetch a unique record that has <code>url = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Businesses fetchOneByUrl(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.Businesses.BUSINESSES.URL, value);
	}

	/**
	 * Fetch records that have <code>btype IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByBtype(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.BTYPE, values);
	}

	/**
	 * Fetch records that have <code>website IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByWebsite(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.WEBSITE, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByPhone(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.PHONE, values);
	}

	/**
	 * Fetch records that have <code>fax IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByFax(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.FAX, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.CREATED, values);
	}

	/**
	 * Fetch records that have <code>updated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByUpdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.UPDATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.STATUS, values);
	}

	/**
	 * Fetch records that have <code>parent_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Businesses> fetchByParentId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Businesses.BUSINESSES.PARENT_ID, values);
	}
}
