/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarFirmwaresDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.CollarFirmwaresRecord, com.petpace.db.jooq.tables.pojos.CollarFirmwares, java.lang.Integer> {

	/**
	 * Create a new CollarFirmwaresDao without any configuration
	 */
	public CollarFirmwaresDao() {
		super(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES, com.petpace.db.jooq.tables.pojos.CollarFirmwares.class);
	}

	/**
	 * Create a new CollarFirmwaresDao with an attached configuration
	 */
	public CollarFirmwaresDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES, com.petpace.db.jooq.tables.pojos.CollarFirmwares.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.CollarFirmwares object) {
		return object.getFirmwareid();
	}

	/**
	 * Fetch records that have <code>FirmwareID IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarFirmwares> fetchByFirmwareid(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.FIRMWAREID, values);
	}

	/**
	 * Fetch a unique record that has <code>FirmwareID = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.CollarFirmwares fetchOneByFirmwareid(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.FIRMWAREID, value);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarFirmwares> fetchByVersion(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.VERSION, values);
	}

	/**
	 * Fetch records that have <code>Comment IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarFirmwares> fetchByComment(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.COMMENT, values);
	}

	/**
	 * Fetch records that have <code>s3 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarFirmwares> fetchByS3(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.S3, values);
	}

	/**
	 * Fetch records that have <code>uploadDate IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarFirmwares> fetchByUploaddate(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.CollarFirmwares.COLLAR_FIRMWARES.UPLOADDATE, values);
	}
}
