/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarRegistrationsDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.CollarRegistrationsRecord, com.petpace.db.jooq.tables.pojos.CollarRegistrations, java.lang.Integer> {

	/**
	 * Create a new CollarRegistrationsDao without any configuration
	 */
	public CollarRegistrationsDao() {
		super(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS, com.petpace.db.jooq.tables.pojos.CollarRegistrations.class);
	}

	/**
	 * Create a new CollarRegistrationsDao with an attached configuration
	 */
	public CollarRegistrationsDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS, com.petpace.db.jooq.tables.pojos.CollarRegistrations.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.CollarRegistrations object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.CollarRegistrations fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>start IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByStart(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.START, values);
	}

	/**
	 * Fetch records that have <code>end IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByEnd(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.END, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.STATUS, values);
	}

	/**
	 * Fetch records that have <code>notes IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.CollarRegistrations> fetchByNotes(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.CollarRegistrations.COLLAR_REGISTRATIONS.NOTES, values);
	}
}
