/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayServersDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.GatewayServersRecord, com.petpace.db.jooq.tables.pojos.GatewayServers, java.lang.Integer> {

	/**
	 * Create a new GatewayServersDao without any configuration
	 */
	public GatewayServersDao() {
		super(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS, com.petpace.db.jooq.tables.pojos.GatewayServers.class);
	}

	/**
	 * Create a new GatewayServersDao with an attached configuration
	 */
	public GatewayServersDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS, com.petpace.db.jooq.tables.pojos.GatewayServers.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.GatewayServers object) {
		return object.getServerid();
	}

	/**
	 * Fetch records that have <code>ServerID IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.GatewayServers> fetchByServerid(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.SERVERID, values);
	}

	/**
	 * Fetch a unique record that has <code>ServerID = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.GatewayServers fetchOneByServerid(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.SERVERID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.GatewayServers> fetchByName(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.NAME, values);
	}

	/**
	 * Fetch a unique record that has <code>name = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.GatewayServers fetchOneByName(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.NAME, value);
	}

	/**
	 * Fetch records that have <code>HostAddr IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.GatewayServers> fetchByHostaddr(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.HOSTADDR, values);
	}

	/**
	 * Fetch records that have <code>version IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.GatewayServers> fetchByVersion(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.VERSION, values);
	}

	/**
	 * Fetch records that have <code>updated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.GatewayServers> fetchByUpdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.UPDATED, values);
	}
}
