/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OwnersDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.OwnersRecord, com.petpace.db.jooq.tables.pojos.Owners, java.lang.Integer> {

	/**
	 * Create a new OwnersDao without any configuration
	 */
	public OwnersDao() {
		super(com.petpace.db.jooq.tables.Owners.OWNERS, com.petpace.db.jooq.tables.pojos.Owners.class);
	}

	/**
	 * Create a new OwnersDao with an attached configuration
	 */
	public OwnersDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Owners.OWNERS, com.petpace.db.jooq.tables.pojos.Owners.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.Owners object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Owners fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Owners.OWNERS.ID, value);
	}

	/**
	 * Fetch records that have <code>account_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByAccountId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.ACCOUNT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>account_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Owners fetchOneByAccountId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Owners.OWNERS.ACCOUNT_ID, value);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByAddressId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.ADDRESS_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>address_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Owners fetchOneByAddressId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Owners.OWNERS.ADDRESS_ID, value);
	}

	/**
	 * Fetch records that have <code>fullname IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByFullname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.FULLNAME, values);
	}

	/**
	 * Fetch records that have <code>email IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByEmail(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.EMAIL, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByPhone(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.PHONE, values);
	}

	/**
	 * Fetch records that have <code>dateCreated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByDatecreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.DATECREATED, values);
	}

	/**
	 * Fetch records that have <code>dateUpdated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByDateupdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.DATEUPDATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Owners> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Owners.OWNERS.STATUS, values);
	}
}
