/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAttributeValueHistoryDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.PetAttributeValueHistoryRecord, com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory, java.lang.Integer> {

	/**
	 * Create a new PetAttributeValueHistoryDao without any configuration
	 */
	public PetAttributeValueHistoryDao() {
		super(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY, com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory.class);
	}

	/**
	 * Create a new PetAttributeValueHistoryDao with an attached configuration
	 */
	public PetAttributeValueHistoryDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY, com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.ID, value);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>val IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByVal(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.VAL, values);
	}

	/**
	 * Fetch records that have <code>dateCreated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByDatecreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.DATECREATED, values);
	}

	/**
	 * Fetch records that have <code>dateUpdated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByDateupdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.DATEUPDATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.STATUS, values);
	}

	/**
	 * Fetch records that have <code>petAttribute_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetAttributeValueHistory> fetchByPetattributeId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetAttributeValueHistory.PET_ATTRIBUTE_VALUE_HISTORY.PETATTRIBUTE_ID, values);
	}
}
