/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetGuardianshipDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.PetGuardianshipRecord, com.petpace.db.jooq.tables.pojos.PetGuardianship, java.lang.Integer> {

	/**
	 * Create a new PetGuardianshipDao without any configuration
	 */
	public PetGuardianshipDao() {
		super(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP, com.petpace.db.jooq.tables.pojos.PetGuardianship.class);
	}

	/**
	 * Create a new PetGuardianshipDao with an attached configuration
	 */
	public PetGuardianshipDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP, com.petpace.db.jooq.tables.pojos.PetGuardianship.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.PetGuardianship object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetGuardianship> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.PetGuardianship fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP.ID, value);
	}

	/**
	 * Fetch records that have <code>guardian_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetGuardianship> fetchByGuardianId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP.GUARDIAN_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetGuardianship> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PetGuardianship> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.PetGuardianship.PET_GUARDIANSHIP.CREATED, values);
	}
}
