/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PostalCodesDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.PostalCodesRecord, com.petpace.db.jooq.tables.pojos.PostalCodes, java.lang.String> {

	/**
	 * Create a new PostalCodesDao without any configuration
	 */
	public PostalCodesDao() {
		super(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES, com.petpace.db.jooq.tables.pojos.PostalCodes.class);
	}

	/**
	 * Create a new PostalCodesDao with an attached configuration
	 */
	public PostalCodesDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES, com.petpace.db.jooq.tables.pojos.PostalCodes.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.String getId(com.petpace.db.jooq.tables.pojos.PostalCodes object) {
		return object.getZipcode();
	}

	/**
	 * Fetch records that have <code>zipcode IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByZipcode(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.ZIPCODE, values);
	}

	/**
	 * Fetch a unique record that has <code>zipcode = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.PostalCodes fetchOneByZipcode(java.lang.String value) {
		return fetchOne(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.ZIPCODE, value);
	}

	/**
	 * Fetch records that have <code>city IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByCity(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.CITY, values);
	}

	/**
	 * Fetch records that have <code>countyName IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByCountyname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.COUNTYNAME, values);
	}

	/**
	 * Fetch records that have <code>regionCode IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByRegioncode(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.REGIONCODE, values);
	}

	/**
	 * Fetch records that have <code>regionFullname IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByRegionfullname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.REGIONFULLNAME, values);
	}

	/**
	 * Fetch records that have <code>countryCode IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByCountrycode(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.COUNTRYCODE, values);
	}

	/**
	 * Fetch records that have <code>countryFullname IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByCountryfullname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.COUNTRYFULLNAME, values);
	}

	/**
	 * Fetch records that have <code>latitude IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByLatitude(java.lang.Double... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.LATITUDE, values);
	}

	/**
	 * Fetch records that have <code>longitude IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByLongitude(java.lang.Double... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.LONGITUDE, values);
	}

	/**
	 * Fetch records that have <code>areaCode IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByAreacode(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.AREACODE, values);
	}

	/**
	 * Fetch records that have <code>timezone IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByTimezone(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.TIMEZONE, values);
	}

	/**
	 * Fetch records that have <code>utc IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.PostalCodes> fetchByUtc(java.lang.Double... values) {
		return fetch(com.petpace.db.jooq.tables.PostalCodes.POSTAL_CODES.UTC, values);
	}
}
