/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VeterinariansDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VeterinariansRecord, com.petpace.db.jooq.tables.pojos.Veterinarians, java.lang.Integer> {

	/**
	 * Create a new VeterinariansDao without any configuration
	 */
	public VeterinariansDao() {
		super(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS, com.petpace.db.jooq.tables.pojos.Veterinarians.class);
	}

	/**
	 * Create a new VeterinariansDao with an attached configuration
	 */
	public VeterinariansDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS, com.petpace.db.jooq.tables.pojos.Veterinarians.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.Veterinarians object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Veterinarians fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ID, value);
	}

	/**
	 * Fetch records that have <code>account_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByAccountId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ACCOUNT_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>account_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Veterinarians fetchOneByAccountId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ACCOUNT_ID, value);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByAddressId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ADDRESS_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>address_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.Veterinarians fetchOneByAddressId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ADDRESS_ID, value);
	}

	/**
	 * Fetch records that have <code>fullName IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByFullname(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.FULLNAME, values);
	}

	/**
	 * Fetch records that have <code>clinic IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByClinic(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.CLINIC, values);
	}

	/**
	 * Fetch records that have <code>prefix IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByPrefix(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.PREFIX, values);
	}

	/**
	 * Fetch records that have <code>suffix IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchBySuffix(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.SUFFIX, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByPhone(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.PHONE, values);
	}

	/**
	 * Fetch records that have <code>cell IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByCell(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.CELL, values);
	}

	/**
	 * Fetch records that have <code>fax IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByFax(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.FAX, values);
	}

	/**
	 * Fetch records that have <code>hours IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByHours(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.HOURS, values);
	}

	/**
	 * Fetch records that have <code>dateCreated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByDatecreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.DATECREATED, values);
	}

	/**
	 * Fetch records that have <code>dateUpdated IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByDateupdated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.DATEUPDATED, values);
	}

	/**
	 * Fetch records that have <code>status IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByStatus(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.STATUS, values);
	}

	/**
	 * Fetch records that have <code>about IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByAbout(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.ABOUT, values);
	}

	/**
	 * Fetch records that have <code>primary_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.Veterinarians> fetchByPrimaryId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS.PRIMARY_ID, values);
	}
}
