/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalPetAttributesDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalPetAttributesRecord, com.petpace.db.jooq.tables.pojos.VitalPetAttributes, java.lang.Integer> {

	/**
	 * Create a new VitalPetAttributesDao without any configuration
	 */
	public VitalPetAttributesDao() {
		super(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES, com.petpace.db.jooq.tables.pojos.VitalPetAttributes.class);
	}

	/**
	 * Create a new VitalPetAttributesDao with an attached configuration
	 */
	public VitalPetAttributesDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES, com.petpace.db.jooq.tables.pojos.VitalPetAttributes.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalPetAttributes object) {
		return object.getPetId();
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.PET_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>pet_id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalPetAttributes fetchOneByPetId(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.PET_ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>samplingFrequency IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchBySamplingfrequency(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.SAMPLINGFREQUENCY, values);
	}

	/**
	 * Fetch records that have <code>battery IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByBattery(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.BATTERY, values);
	}

	/**
	 * Fetch records that have <code>buckle IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByBuckle(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.BUCKLE, values);
	}

	/**
	 * Fetch records that have <code>charging IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByCharging(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.CHARGING, values);
	}

	/**
	 * Fetch records that have <code>ambientTemp IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByAmbienttemp(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.AMBIENTTEMP, values);
	}

	/**
	 * Fetch records that have <code>bodyTemp IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByBodytemp(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.BODYTEMP, values);
	}

	/**
	 * Fetch records that have <code>pulse IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByPulse(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.PULSE, values);
	}

	/**
	 * Fetch records that have <code>respiratory IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByRespiratory(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.RESPIRATORY, values);
	}

	/**
	 * Fetch records that have <code>activity IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByActivity(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.ACTIVITY, values);
	}

	/**
	 * Fetch records that have <code>position IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByPosition(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.POSITION, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.TIME, values);
	}

	/**
	 * Fetch records that have <code>lastCommunication IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByLastcommunication(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.LASTCOMMUNICATION, values);
	}

	/**
	 * Fetch records that have <code>sendNotification IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchBySendnotification(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.SENDNOTIFICATION, values);
	}

	/**
	 * Fetch records that have <code>clinicalTrial IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPetAttributes> fetchByClinicaltrial(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPetAttributes.VITAL_PET_ATTRIBUTES.CLINICALTRIAL, values);
	}
}
