/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalActivityMinuteDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalActivityMinuteRecord, com.petpace.db.jooq.tables.pojos.VitalActivityMinute, java.lang.Integer> {

	/**
	 * Create a new VitalActivityMinuteDao without any configuration
	 */
	public VitalActivityMinuteDao() {
		super(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE, com.petpace.db.jooq.tables.pojos.VitalActivityMinute.class);
	}

	/**
	 * Create a new VitalActivityMinuteDao with an attached configuration
	 */
	public VitalActivityMinuteDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE, com.petpace.db.jooq.tables.pojos.VitalActivityMinute.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalActivityMinute object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalActivityMinute fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchByValue(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.VALUE, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.SMV30, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivityMinute> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivityMinute.VITAL_ACTIVITY_MINUTE.TIME, values);
	}
}
