/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalRespiratoryMinuteDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalRespiratoryMinuteRecord, com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute, java.lang.Integer> {

	/**
	 * Create a new VitalRespiratoryMinuteDao without any configuration
	 */
	public VitalRespiratoryMinuteDao() {
		super(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE, com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute.class);
	}

	/**
	 * Create a new VitalRespiratoryMinuteDao with an attached configuration
	 */
	public VitalRespiratoryMinuteDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE, com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchByValue(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.VALUE, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.SMV30, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalRespiratoryMinute> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.TIME, values);
	}
}
