/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalBodytempDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalBodytempRecord, com.petpace.db.jooq.tables.pojos.VitalBodytemp, java.lang.Integer> {

	/**
	 * Create a new VitalBodytempDao without any configuration
	 */
	public VitalBodytempDao() {
		super(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP, com.petpace.db.jooq.tables.pojos.VitalBodytemp.class);
	}

	/**
	 * Create a new VitalBodytempDao with an attached configuration
	 */
	public VitalBodytempDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP, com.petpace.db.jooq.tables.pojos.VitalBodytemp.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalBodytemp object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalBodytemp fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByName(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.NAME, values);
	}

	/**
	 * Fetch records that have <code>quality IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByQuality(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.QUALITY, values);
	}

	/**
	 * Fetch records that have <code>deviation IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByDeviation(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.DEVIATION, values);
	}

	/**
	 * Fetch records that have <code>duration IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByDuration(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.DURATION, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByValue(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.VALUE, values);
	}

	/**
	 * Fetch records that have <code>ambient IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByAmbient(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.AMBIENT, values);
	}

	/**
	 * Fetch records that have <code>hiLimit IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByHilimit(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.HILIMIT, values);
	}

	/**
	 * Fetch records that have <code>lowLimit IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByLowlimit(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.LOWLIMIT, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.SMV30, values);
	}

	/**
	 * Fetch records that have <code>exhale IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByExhale(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.EXHALE, values);
	}

	/**
	 * Fetch records that have <code>exhale_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByExhaleStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.EXHALE_STD, values);
	}

	/**
	 * Fetch records that have <code>inhale IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByInhale(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.INHALE, values);
	}

	/**
	 * Fetch records that have <code>inhale_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByInhaleStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.INHALE_STD, values);
	}

	/**
	 * Fetch records that have <code>nn IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByNn(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.NN, values);
	}

	/**
	 * Fetch records that have <code>nn_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByNnStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.NN_STD, values);
	}

	/**
	 * Fetch records that have <code>ipr IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByIpr(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.IPR, values);
	}

	/**
	 * Fetch records that have <code>ipr_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByIprStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.IPR_STD, values);
	}

	/**
	 * Fetch records that have <code>debug IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByDebug(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.DEBUG, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.TIME, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.CREATED, values);
	}

	/**
	 * Fetch records that have <code>notes IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytemp> fetchByNotes(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytemp.VITAL_BODYTEMP.NOTES, values);
	}
}
