/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalActivityDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalActivityRecord, com.petpace.db.jooq.tables.pojos.VitalActivity, java.lang.Integer> {

	/**
	 * Create a new VitalActivityDao without any configuration
	 */
	public VitalActivityDao() {
		super(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY, com.petpace.db.jooq.tables.pojos.VitalActivity.class);
	}

	/**
	 * Create a new VitalActivityDao with an attached configuration
	 */
	public VitalActivityDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY, com.petpace.db.jooq.tables.pojos.VitalActivity.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalActivity object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalActivity fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByName(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.NAME, values);
	}

	/**
	 * Fetch records that have <code>quality IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByQuality(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.QUALITY, values);
	}

	/**
	 * Fetch records that have <code>deviation IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByDeviation(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.DEVIATION, values);
	}

	/**
	 * Fetch records that have <code>duration IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByDuration(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.DURATION, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByValue(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.VALUE, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.SMV30, values);
	}

	/**
	 * Fetch records that have <code>debug IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByDebug(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.DEBUG, values);
	}

	/**
	 * Fetch records that have <code>exhale IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByExhale(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.EXHALE, values);
	}

	/**
	 * Fetch records that have <code>exhale_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByExhaleStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.EXHALE_STD, values);
	}

	/**
	 * Fetch records that have <code>inhale IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByInhale(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.INHALE, values);
	}

	/**
	 * Fetch records that have <code>inhale_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByInhaleStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.INHALE_STD, values);
	}

	/**
	 * Fetch records that have <code>nn IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByNn(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.NN, values);
	}

	/**
	 * Fetch records that have <code>nn_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByNnStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.NN_STD, values);
	}

	/**
	 * Fetch records that have <code>ipr IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByIpr(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.IPR, values);
	}

	/**
	 * Fetch records that have <code>ipr_std IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByIprStd(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.IPR_STD, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.TIME, values);
	}

	/**
	 * Fetch records that have <code>created IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByCreated(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.CREATED, values);
	}

	/**
	 * Fetch records that have <code>notes IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalActivity> fetchByNotes(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalActivity.VITAL_ACTIVITY.NOTES, values);
	}
}
