/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalBodytempHourDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, com.petpace.db.jooq.tables.pojos.VitalBodytempHour, java.lang.Integer> {

	/**
	 * Create a new VitalBodytempHourDao without any configuration
	 */
	public VitalBodytempHourDao() {
		super(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR, com.petpace.db.jooq.tables.pojos.VitalBodytempHour.class);
	}

	/**
	 * Create a new VitalBodytempHourDao with an attached configuration
	 */
	public VitalBodytempHourDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR, com.petpace.db.jooq.tables.pojos.VitalBodytempHour.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalBodytempHour object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalBodytempHour fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByValue(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.VALUE, values);
	}

	/**
	 * Fetch records that have <code>ambient IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByAmbient(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.AMBIENT, values);
	}

	/**
	 * Fetch records that have <code>hiLimit IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByHilimit(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.HILIMIT, values);
	}

	/**
	 * Fetch records that have <code>lowLimit IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByLowlimit(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.LOWLIMIT, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.SMV30, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalBodytempHour> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR.TIME, values);
	}
}
