/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.daos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalPulseMinuteDao extends org.jooq.impl.DAOImpl<com.petpace.db.jooq.tables.records.VitalPulseMinuteRecord, com.petpace.db.jooq.tables.pojos.VitalPulseMinute, java.lang.Integer> {

	/**
	 * Create a new VitalPulseMinuteDao without any configuration
	 */
	public VitalPulseMinuteDao() {
		super(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE, com.petpace.db.jooq.tables.pojos.VitalPulseMinute.class);
	}

	/**
	 * Create a new VitalPulseMinuteDao with an attached configuration
	 */
	public VitalPulseMinuteDao(org.jooq.Configuration configuration) {
		super(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE, com.petpace.db.jooq.tables.pojos.VitalPulseMinute.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected java.lang.Integer getId(com.petpace.db.jooq.tables.pojos.VitalPulseMinute object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchById(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public com.petpace.db.jooq.tables.pojos.VitalPulseMinute fetchOneById(java.lang.Integer value) {
		return fetchOne(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.ID, value);
	}

	/**
	 * Fetch records that have <code>collar_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchByCollarId(java.lang.String... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.COLLAR_ID, values);
	}

	/**
	 * Fetch records that have <code>pet_id IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchByPetId(java.lang.Integer... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.PET_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchByValue(java.lang.Long... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.VALUE, values);
	}

	/**
	 * Fetch records that have <code>smv10 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchBySmv10(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.SMV10, values);
	}

	/**
	 * Fetch records that have <code>smv30 IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchBySmv30(java.math.BigDecimal... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.SMV30, values);
	}

	/**
	 * Fetch records that have <code>time IN (values)</code>
	 */
	public java.util.List<com.petpace.db.jooq.tables.pojos.VitalPulseMinute> fetchByTime(java.sql.Timestamp... values) {
		return fetch(com.petpace.db.jooq.tables.VitalPulseMinute.VITAL_PULSE_MINUTE.TIME, values);
	}
}
