/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.AddressRecord> implements org.jooq.Record10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = 169366019;

	/**
	 * Setter for <code>sirius.address.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sirius.address.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sirius.address.street</code>. 
	 */
	public void setStreet(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sirius.address.street</code>. 
	 */
	public java.lang.String getStreet() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sirius.address.street2</code>. 
	 */
	public void setStreet2(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sirius.address.street2</code>. 
	 */
	public java.lang.String getStreet2() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sirius.address.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sirius.address.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sirius.address.region</code>. 
	 */
	public void setRegion(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sirius.address.region</code>. 
	 */
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sirius.address.country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sirius.address.country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sirius.address.zipcode</code>. 
	 */
	public void setZipcode(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sirius.address.zipcode</code>. 
	 */
	public java.lang.String getZipcode() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sirius.address.dateCreated</code>. 
	 */
	public void setDatecreated(java.sql.Timestamp value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sirius.address.dateCreated</code>. 
	 */
	public java.sql.Timestamp getDatecreated() {
		return (java.sql.Timestamp) getValue(7);
	}

	/**
	 * Setter for <code>sirius.address.dateUpdated</code>. 
	 */
	public void setDateupdated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sirius.address.dateUpdated</code>. 
	 */
	public java.sql.Timestamp getDateupdated() {
		return (java.sql.Timestamp) getValue(8);
	}

	/**
	 * Setter for <code>sirius.address.status</code>. 
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sirius.address.status</code>. 
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(9);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record10 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row10) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row10<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row10) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.STREET;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.STREET2;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.ZIPCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field8() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.DATEUPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field10() {
		return com.petpace.db.jooq.tables.Address.ADDRESS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getStreet();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getStreet2();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getZipcode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value8() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getDateupdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value10() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AddressRecord
	 */
	public AddressRecord() {
		super(com.petpace.db.jooq.tables.Address.ADDRESS);
	}
}
