/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertsRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.AlertsRecord> implements org.jooq.Record9<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp> {

	private static final long serialVersionUID = -738865788;

	/**
	 * Setter for <code>rigel.alerts.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rigel.alerts.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rigel.alerts.rule_id</code>. 
	 */
	public void setRuleId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rigel.alerts.rule_id</code>. 
	 */
	public java.lang.Integer getRuleId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>rigel.alerts.collar_id</code>. 
	 */
	public void setCollarId(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rigel.alerts.collar_id</code>. 
	 */
	public java.lang.String getCollarId() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rigel.alerts.pet_id</code>. 
	 */
	public void setPetId(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rigel.alerts.pet_id</code>. 
	 */
	public java.lang.Integer getPetId() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>rigel.alerts.sensor_id</code>. 
	 */
	public void setSensorId(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rigel.alerts.sensor_id</code>. 
	 */
	public java.lang.Integer getSensorId() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>rigel.alerts.message</code>. 
	 */
	public void setMessage(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rigel.alerts.message</code>. 
	 */
	public java.lang.String getMessage() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>rigel.alerts.data</code>. 
	 */
	public void setData(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>rigel.alerts.data</code>. 
	 */
	public java.lang.String getData() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>rigel.alerts.processed</code>. 
	 */
	public void setProcessed(java.lang.Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>rigel.alerts.processed</code>. 
	 */
	public java.lang.Integer getProcessed() {
		return (java.lang.Integer) getValue(7);
	}

	/**
	 * Setter for <code>rigel.alerts.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>rigel.alerts.created</code>. 
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(8);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row9) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row9<java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row9) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.RULE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.COLLAR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.PET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.SENSOR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.MESSAGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field8() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.PROCESSED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field9() {
		return com.petpace.db.jooq.tables.Alerts.ALERTS.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getRuleId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCollarId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getPetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getSensorId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getMessage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value8() {
		return getProcessed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value9() {
		return getCreated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AlertsRecord
	 */
	public AlertsRecord() {
		super(com.petpace.db.jooq.tables.Alerts.ALERTS);
	}
}
