/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarGroupsRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.CollarGroupsRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -630467198;

	/**
	 * Setter for <code>rigel.collar_groups.GroupID</code>. 
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rigel.collar_groups.GroupID</code>. 
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rigel.collar_groups.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rigel.collar_groups.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rigel.collar_groups.Comment</code>. 
	 */
	public void setComment(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rigel.collar_groups.Comment</code>. 
	 */
	public java.lang.String getComment() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rigel.collar_groups.FirmwareID</code>. 
	 */
	public void setFirmwareid(java.lang.Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rigel.collar_groups.FirmwareID</code>. 
	 */
	public java.lang.Integer getFirmwareid() {
		return (java.lang.Integer) getValue(3);
	}

	/**
	 * Setter for <code>rigel.collar_groups.ConfigID</code>. 
	 */
	public void setConfigid(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rigel.collar_groups.ConfigID</code>. 
	 */
	public java.lang.Integer getConfigid() {
		return (java.lang.Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS.COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field4() {
		return com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS.FIRMWAREID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS.CONFIGID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value4() {
		return getFirmwareid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getConfigid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CollarGroupsRecord
	 */
	public CollarGroupsRecord() {
		super(com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS);
	}
}
