/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarsRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.CollarsRecord> implements org.jooq.Record13<java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer> {

	private static final long serialVersionUID = 1872363445;

	/**
	 * Setter for <code>sirius.collars.id</code>. 
	 */
	public void setId(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sirius.collars.id</code>. 
	 */
	public java.lang.String getId() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>sirius.collars.Authorized</code>. 
	 */
	public void setAuthorized(java.lang.Short value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sirius.collars.Authorized</code>. 
	 */
	public java.lang.Short getAuthorized() {
		return (java.lang.Short) getValue(1);
	}

	/**
	 * Setter for <code>sirius.collars.BatteryLevel</code>. 
	 */
	public void setBatterylevel(java.lang.Short value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sirius.collars.BatteryLevel</code>. 
	 */
	public java.lang.Short getBatterylevel() {
		return (java.lang.Short) getValue(2);
	}

	/**
	 * Setter for <code>sirius.collars.State</code>. 
	 */
	public void setState(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sirius.collars.State</code>. 
	 */
	public java.lang.String getState() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sirius.collars.HWVersion</code>. 
	 */
	public void setHwversion(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sirius.collars.HWVersion</code>. 
	 */
	public java.lang.String getHwversion() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>sirius.collars.CurrFWVersion</code>. 
	 */
	public void setCurrfwversion(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>sirius.collars.CurrFWVersion</code>. 
	 */
	public java.lang.String getCurrfwversion() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>sirius.collars.CurrConfVersion</code>. 
	 */
	public void setCurrconfversion(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>sirius.collars.CurrConfVersion</code>. 
	 */
	public java.lang.String getCurrconfversion() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>sirius.collars.WantSupport</code>. 
	 */
	public void setWantsupport(java.lang.Short value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>sirius.collars.WantSupport</code>. 
	 */
	public java.lang.Short getWantsupport() {
		return (java.lang.Short) getValue(7);
	}

	/**
	 * Setter for <code>sirius.collars.Cookie</code>. 
	 */
	public void setCookie(java.lang.String value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>sirius.collars.Cookie</code>. 
	 */
	public java.lang.String getCookie() {
		return (java.lang.String) getValue(8);
	}

	/**
	 * Setter for <code>sirius.collars.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>sirius.collars.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(9);
	}

	/**
	 * Setter for <code>sirius.collars.GroupID</code>. 
	 */
	public void setGroupid(java.lang.Integer value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>sirius.collars.GroupID</code>. 
	 */
	public java.lang.Integer getGroupid() {
		return (java.lang.Integer) getValue(10);
	}

	/**
	 * Setter for <code>sirius.collars.InputRef</code>. 
	 */
	public void setInputref(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>sirius.collars.InputRef</code>. 
	 */
	public java.lang.String getInputref() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>sirius.collars.GatewayID</code>. 
	 */
	public void setGatewayid(java.lang.Integer value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>sirius.collars.GatewayID</code>. 
	 */
	public java.lang.Integer getGatewayid() {
		return (java.lang.Integer) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.String, java.lang.Short, java.lang.Short, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Short, java.lang.String, java.sql.Timestamp, java.lang.Integer, java.lang.String, java.lang.Integer> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field2() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.AUTHORIZED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field3() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.BATTERYLEVEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.STATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.HWVERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.CURRFWVERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.CURRCONFVERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Short> field8() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.WANTSUPPORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field9() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.COOKIE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field10() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field11() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.GROUPID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.INPUTREF;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field13() {
		return com.petpace.db.jooq.tables.Collars.COLLARS.GATEWAYID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value2() {
		return getAuthorized();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value3() {
		return getBatterylevel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getState();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getHwversion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCurrfwversion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getCurrconfversion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Short value8() {
		return getWantsupport();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value9() {
		return getCookie();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value10() {
		return getUpdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value11() {
		return getGroupid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getInputref();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value13() {
		return getGatewayid();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CollarsRecord
	 */
	public CollarsRecord() {
		super(com.petpace.db.jooq.tables.Collars.COLLARS);
	}
}
