/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayServersRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.GatewayServersRecord> implements org.jooq.Record5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> {

	private static final long serialVersionUID = -1420909806;

	/**
	 * Setter for <code>sirius.gateway_servers.ServerID</code>. 
	 */
	public void setServerid(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sirius.gateway_servers.ServerID</code>. 
	 */
	public java.lang.Integer getServerid() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sirius.gateway_servers.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sirius.gateway_servers.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>sirius.gateway_servers.HostAddr</code>. 
	 */
	public void setHostaddr(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sirius.gateway_servers.HostAddr</code>. 
	 */
	public java.lang.String getHostaddr() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>sirius.gateway_servers.version</code>. 
	 */
	public void setVersion(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>sirius.gateway_servers.version</code>. 
	 */
	public java.lang.String getVersion() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>sirius.gateway_servers.updated</code>. 
	 */
	public void setUpdated(java.sql.Timestamp value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>sirius.gateway_servers.updated</code>. 
	 */
	public java.sql.Timestamp getUpdated() {
		return (java.sql.Timestamp) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.SERVERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.HOSTADDR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.VERSION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field5() {
		return com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS.UPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getServerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getHostaddr();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getVersion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value5() {
		return getUpdated();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached GatewayServersRecord
	 */
	public GatewayServersRecord() {
		super(com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS);
	}
}
