/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAttributeGroupingRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.PetAttributeGroupingRecord> implements org.jooq.Record3<java.lang.Integer, java.lang.Integer, java.lang.Integer> {

	private static final long serialVersionUID = -1304416924;

	/**
	 * Setter for <code>sirius.pet_attribute_grouping.group_id</code>. 
	 */
	public void setGroupId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>sirius.pet_attribute_grouping.group_id</code>. 
	 */
	public java.lang.Integer getGroupId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>sirius.pet_attribute_grouping.attribute_id</code>. 
	 */
	public void setAttributeId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>sirius.pet_attribute_grouping.attribute_id</code>. 
	 */
	public java.lang.Integer getAttributeId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>sirius.pet_attribute_grouping.sort</code>. 
	 */
	public void setSort(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>sirius.pet_attribute_grouping.sort</code>. 
	 */
	public java.lang.Integer getSort() {
		return (java.lang.Integer) getValue(2);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record2<java.lang.Integer, java.lang.Integer> key() {
		return (org.jooq.Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record3 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row3) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row3<java.lang.Integer, java.lang.Integer, java.lang.Integer> valuesRow() {
		return (org.jooq.Row3) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.PetAttributeGrouping.PET_ATTRIBUTE_GROUPING.GROUP_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return com.petpace.db.jooq.tables.PetAttributeGrouping.PET_ATTRIBUTE_GROUPING.ATTRIBUTE_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.petpace.db.jooq.tables.PetAttributeGrouping.PET_ATTRIBUTE_GROUPING.SORT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getGroupId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getAttributeId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getSort();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PetAttributeGroupingRecord
	 */
	public PetAttributeGroupingRecord() {
		super(com.petpace.db.jooq.tables.PetAttributeGrouping.PET_ATTRIBUTE_GROUPING);
	}
}
