/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceProvincesRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.PlaceProvincesRecord> implements org.jooq.Record4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> {

	private static final long serialVersionUID = 734427293;

	/**
	 * Setter for <code>rigel.place_provinces.provinceCode</code>. 
	 */
	public void setProvincecode(java.lang.String value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rigel.place_provinces.provinceCode</code>. 
	 */
	public java.lang.String getProvincecode() {
		return (java.lang.String) getValue(0);
	}

	/**
	 * Setter for <code>rigel.place_provinces.province</code>. 
	 */
	public void setProvince(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rigel.place_provinces.province</code>. 
	 */
	public java.lang.String getProvince() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rigel.place_provinces.country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rigel.place_provinces.country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rigel.place_provinces.countryCode</code>. 
	 */
	public void setCountrycode(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rigel.place_provinces.countryCode</code>. 
	 */
	public java.lang.String getCountrycode() {
		return (java.lang.String) getValue(3);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.String> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> fieldsRow() {
		return (org.jooq.Row4) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row4<java.lang.String, java.lang.String, java.lang.String, java.lang.String> valuesRow() {
		return (org.jooq.Row4) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field1() {
		return com.petpace.db.jooq.tables.PlaceProvinces.PLACE_PROVINCES.PROVINCECODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.PlaceProvinces.PLACE_PROVINCES.PROVINCE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.PlaceProvinces.PLACE_PROVINCES.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.petpace.db.jooq.tables.PlaceProvinces.PLACE_PROVINCES.COUNTRYCODE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value1() {
		return getProvincecode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getProvince();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getCountrycode();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaceProvincesRecord
	 */
	public PlaceProvincesRecord() {
		super(com.petpace.db.jooq.tables.PlaceProvinces.PLACE_PROVINCES);
	}
}
