/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceNeighborhoodsRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.PlaceNeighborhoodsRecord> implements org.jooq.Record12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.sql.Timestamp, java.lang.Integer> {

	private static final long serialVersionUID = -335941370;

	/**
	 * Setter for <code>rigel.place_neighborhoods.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.name</code>. 
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.name</code>. 
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.sub</code>. 
	 */
	public void setSub(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.sub</code>. 
	 */
	public java.lang.String getSub() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.display</code>. 
	 */
	public void setDisplay(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.display</code>. 
	 */
	public java.lang.String getDisplay() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.url</code>. 
	 */
	public void setUrl(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.url</code>. 
	 */
	public java.lang.String getUrl() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.city</code>. 
	 */
	public void setCity(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.city</code>. 
	 */
	public java.lang.String getCity() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.region</code>. 
	 */
	public void setRegion(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.region</code>. 
	 */
	public java.lang.String getRegion() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.country</code>. 
	 */
	public void setCountry(java.lang.String value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.country</code>. 
	 */
	public java.lang.String getCountry() {
		return (java.lang.String) getValue(7);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.latitude</code>. 
	 */
	public void setLatitude(java.lang.Double value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.latitude</code>. 
	 */
	public java.lang.Double getLatitude() {
		return (java.lang.Double) getValue(8);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.longitude</code>. 
	 */
	public void setLongitude(java.lang.Double value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.longitude</code>. 
	 */
	public java.lang.Double getLongitude() {
		return (java.lang.Double) getValue(9);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.created</code>. 
	 */
	public void setCreated(java.sql.Timestamp value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.created</code>. 
	 */
	public java.sql.Timestamp getCreated() {
		return (java.sql.Timestamp) getValue(10);
	}

	/**
	 * Setter for <code>rigel.place_neighborhoods.status</code>. 
	 */
	public void setStatus(java.lang.Integer value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>rigel.place_neighborhoods.status</code>. 
	 */
	public java.lang.Integer getStatus() {
		return (java.lang.Integer) getValue(11);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record12 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.sql.Timestamp, java.lang.Integer> fieldsRow() {
		return (org.jooq.Row12) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row12<java.lang.Integer, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Double, java.lang.Double, java.sql.Timestamp, java.lang.Integer> valuesRow() {
		return (org.jooq.Row12) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.SUB;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.DISPLAY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.URL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.CITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.REGION;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field8() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.COUNTRY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field9() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.LATITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Double> field10() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.LONGITUDE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field11() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.CREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field12() {
		return com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS.STATUS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getSub();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getDisplay();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getUrl();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getCity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getRegion();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value8() {
		return getCountry();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value9() {
		return getLatitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Double value10() {
		return getLongitude();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value11() {
		return getCreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value12() {
		return getStatus();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PlaceNeighborhoodsRecord
	 */
	public PlaceNeighborhoodsRecord() {
		super(com.petpace.db.jooq.tables.PlaceNeighborhoods.PLACE_NEIGHBORHOODS);
	}
}
