/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalRespiratoryMinuteRecord extends org.jooq.impl.UpdatableRecordImpl<com.petpace.db.jooq.tables.records.VitalRespiratoryMinuteRecord> implements org.jooq.Record7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.sql.Timestamp> {

	private static final long serialVersionUID = 968794516;

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.id</code>. 
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.id</code>. 
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.collar_id</code>. 
	 */
	public void setCollarId(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.collar_id</code>. 
	 */
	public java.lang.String getCollarId() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.pet_id</code>. 
	 */
	public void setPetId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.pet_id</code>. 
	 */
	public java.lang.Integer getPetId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.value</code>. 
	 */
	public void setValue(java.lang.Long value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.value</code>. 
	 */
	public java.lang.Long getValue() {
		return (java.lang.Long) getValue(3);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.smv10</code>. 
	 */
	public void setSmv10(java.math.BigDecimal value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.smv10</code>. 
	 */
	public java.math.BigDecimal getSmv10() {
		return (java.math.BigDecimal) getValue(4);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.smv30</code>. 
	 */
	public void setSmv30(java.math.BigDecimal value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.smv30</code>. 
	 */
	public java.math.BigDecimal getSmv30() {
		return (java.math.BigDecimal) getValue(5);
	}

	/**
	 * Setter for <code>rigel.vital_respiratory_minute.time</code>. 
	 */
	public void setTime(java.sql.Timestamp value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>rigel.vital_respiratory_minute.time</code>. 
	 */
	public java.sql.Timestamp getTime() {
		return (java.sql.Timestamp) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.sql.Timestamp> fieldsRow() {
		return (org.jooq.Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row7<java.lang.Integer, java.lang.String, java.lang.Integer, java.lang.Long, java.math.BigDecimal, java.math.BigDecimal, java.sql.Timestamp> valuesRow() {
		return (org.jooq.Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.COLLAR_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.PET_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field4() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field5() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.SMV10;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.math.BigDecimal> field6() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.SMV30;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.sql.Timestamp> field7() {
		return com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE.TIME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getCollarId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getPetId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value4() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value5() {
		return getSmv10();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.math.BigDecimal value6() {
		return getSmv30();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.sql.Timestamp value7() {
		return getTime();
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached VitalRespiratoryMinuteRecord
	 */
	public VitalRespiratoryMinuteRecord() {
		super(com.petpace.db.jooq.tables.VitalRespiratoryMinute.VITAL_RESPIRATORY_MINUTE);
	}
}
