/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationPreferences extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord> {

	private static final long serialVersionUID = 1218657714;

	/**
	 * The singleton instance of <code>rigel.alert_notification_preferences</code>
	 */
	public static final com.petpace.db.jooq.tables.AlertNotificationPreferences ALERT_NOTIFICATION_PREFERENCES = new com.petpace.db.jooq.tables.AlertNotificationPreferences();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord.class;
	}

	/**
	 * The column <code>rigel.alert_notification_preferences.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.phoneList</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.String> PHONELIST = createField("phoneList", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.emailList</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.String> EMAILLIST = createField("emailList", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.smsList</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.String> SMSLIST = createField("smsList", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.created</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.updated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.alert_notification_preferences.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.alert_notification_preferences</code> table reference
	 */
	public AlertNotificationPreferences() {
		super("alert_notification_preferences", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.alert_notification_preferences</code> table reference
	 */
	public AlertNotificationPreferences(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.AlertNotificationPreferences.ALERT_NOTIFICATION_PREFERENCES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_ALERT_NOTIFICATION_PREFERENCES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_PREFERENCES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencesRecord>>asList(com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_PREFERENCES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.AlertNotificationPreferences as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.AlertNotificationPreferences(alias);
	}
}
