/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationPreferencePets extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord> {

	private static final long serialVersionUID = -32025415;

	/**
	 * The singleton instance of <code>sirius.alert_notification_preference_pets</code>
	 */
	public static final com.petpace.db.jooq.tables.AlertNotificationPreferencePets ALERT_NOTIFICATION_PREFERENCE_PETS = new com.petpace.db.jooq.tables.AlertNotificationPreferencePets();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord.class;
	}

	/**
	 * The column <code>sirius.alert_notification_preference_pets.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.alert_notification_preference_pets.preference_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord, java.lang.Integer> PREFERENCE_ID = createField("preference_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.alert_notification_preference_pets.businessUnit_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord, java.lang.Integer> BUSINESSUNIT_ID = createField("businessUnit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sirius.alert_notification_preference_pets</code> table reference
	 */
	public AlertNotificationPreferencePets() {
		super("alert_notification_preference_pets", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.alert_notification_preference_pets</code> table reference
	 */
	public AlertNotificationPreferencePets(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.AlertNotificationPreferencePets.ALERT_NOTIFICATION_PREFERENCE_PETS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_PREFERENCE_PETS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord>>asList(com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_PREFERENCE_PETS_PRIMARY, com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_PREFERENCE_PETS_UNIQ_46603D08D81022C0);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertNotificationPreferencePetsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_46603D08966F7FB6, com.petpace.db.jooq.Keys.FK_46603D08D81022C0, com.petpace.db.jooq.Keys.FK_46603D089593E1E8);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.AlertNotificationPreferencePets as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.AlertNotificationPreferencePets(alias);
	}
}
