/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationBusinessUnits extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord> {

	private static final long serialVersionUID = 1664981956;

	/**
	 * The singleton instance of <code>rigel.alert_notification_business_units</code>
	 */
	public static final com.petpace.db.jooq.tables.AlertNotificationBusinessUnits ALERT_NOTIFICATION_BUSINESS_UNITS = new com.petpace.db.jooq.tables.AlertNotificationBusinessUnits();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord.class;
	}

	/**
	 * The column <code>rigel.alert_notification_business_units.preference_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord, java.lang.Integer> PREFERENCE_ID = createField("preference_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alert_notification_business_units.businessUnit_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord, java.lang.Integer> BUSINESSUNIT_ID = createField("businessUnit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.alert_notification_business_units</code> table reference
	 */
	public AlertNotificationBusinessUnits() {
		super("alert_notification_business_units", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.alert_notification_business_units</code> table reference
	 */
	public AlertNotificationBusinessUnits(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.AlertNotificationBusinessUnits.ALERT_NOTIFICATION_BUSINESS_UNITS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_BUSINESS_UNITS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord>>asList(com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_BUSINESS_UNITS_PRIMARY, com.petpace.db.jooq.Keys.KEY_ALERT_NOTIFICATION_BUSINESS_UNITS_UNIQ_8582B388D81022C0);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertNotificationBusinessUnitsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_8582B388D81022C0, com.petpace.db.jooq.Keys.FK_8582B3889593E1E8);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.AlertNotificationBusinessUnits as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.AlertNotificationBusinessUnits(alias);
	}
}
