/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertRules extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.AlertRulesRecord> {

	private static final long serialVersionUID = -1990592379;

	/**
	 * The singleton instance of <code>sirius.alert_rules</code>
	 */
	public static final com.petpace.db.jooq.tables.AlertRules ALERT_RULES = new com.petpace.db.jooq.tables.AlertRules();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.AlertRulesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.AlertRulesRecord.class;
	}

	/**
	 * The column <code>sirius.alert_rules.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.alert_rules.name</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.alert_rules.sensor</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.String> SENSOR = createField("sensor", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.alert_rules.description</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.String> DESCRIPTION = createField("description", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.alert_rules.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.alert_rules.created</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.alert_rules</code> table reference
	 */
	public AlertRules() {
		super("alert_rules", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.alert_rules</code> table reference
	 */
	public AlertRules(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.AlertRules.ALERT_RULES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.AlertRulesRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_ALERT_RULES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertRulesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ALERT_RULES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertRulesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertRulesRecord>>asList(com.petpace.db.jooq.Keys.KEY_ALERT_RULES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.AlertRules as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.AlertRules(alias);
	}
}
