/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alerts extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.AlertsRecord> {

	private static final long serialVersionUID = 1331703623;

	/**
	 * The singleton instance of <code>rigel.alerts</code>
	 */
	public static final com.petpace.db.jooq.tables.Alerts ALERTS = new com.petpace.db.jooq.tables.Alerts();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.AlertsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.AlertsRecord.class;
	}

	/**
	 * The column <code>rigel.alerts.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alerts.rule_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> RULE_ID = createField("rule_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alerts.collar_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.String> COLLAR_ID = createField("collar_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.alerts.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alerts.sensor_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> SENSOR_ID = createField("sensor_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alerts.message</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.alerts.data</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>rigel.alerts.processed</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> PROCESSED = createField("processed", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.alerts.created</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.AlertsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>rigel.alerts</code> table reference
	 */
	public Alerts() {
		super("alerts", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.alerts</code> table reference
	 */
	public Alerts(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.Alerts.ALERTS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.AlertsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_ALERTS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ALERTS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.AlertsRecord>>asList(com.petpace.db.jooq.Keys.KEY_ALERTS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.AlertsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_F77AC06B744E0351, com.petpace.db.jooq.Keys.FK_F77AC06B4568D8A0, com.petpace.db.jooq.Keys.FK_F77AC06B966F7FB6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.Alerts as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.Alerts(alias);
	}
}
