/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedAttributes extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.BreedAttributesRecord> {

	private static final long serialVersionUID = -710157500;

	/**
	 * The singleton instance of <code>sirius.breed_attributes</code>
	 */
	public static final com.petpace.db.jooq.tables.BreedAttributes BREED_ATTRIBUTES = new com.petpace.db.jooq.tables.BreedAttributes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.BreedAttributesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.BreedAttributesRecord.class;
	}

	/**
	 * The column <code>sirius.breed_attributes.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BreedAttributesRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.breed_attributes.dataType</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BreedAttributesRecord, java.lang.String> DATATYPE = createField("dataType", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * Create a <code>sirius.breed_attributes</code> table reference
	 */
	public BreedAttributes() {
		super("breed_attributes", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.breed_attributes</code> table reference
	 */
	public BreedAttributes(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.BreedAttributes.BREED_ATTRIBUTES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BreedAttributesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_BREED_ATTRIBUTES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BreedAttributesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BreedAttributesRecord>>asList(com.petpace.db.jooq.Keys.KEY_BREED_ATTRIBUTES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.BreedAttributes as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.BreedAttributes(alias);
	}
}
