/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessUnitAdministrators extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord> {

	private static final long serialVersionUID = 639224203;

	/**
	 * The singleton instance of <code>rigel.business_unit_administrators</code>
	 */
	public static final com.petpace.db.jooq.tables.BusinessUnitAdministrators BUSINESS_UNIT_ADMINISTRATORS = new com.petpace.db.jooq.tables.BusinessUnitAdministrators();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord.class;
	}

	/**
	 * The column <code>rigel.business_unit_administrators.business_unit_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord, java.lang.Integer> BUSINESS_UNIT_ID = createField("business_unit_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.business_unit_administrators.account_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.business_unit_administrators</code> table reference
	 */
	public BusinessUnitAdministrators() {
		super("business_unit_administrators", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.business_unit_administrators</code> table reference
	 */
	public BusinessUnitAdministrators(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.BusinessUnitAdministrators.BUSINESS_UNIT_ADMINISTRATORS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_BUSINESS_UNIT_ADMINISTRATORS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord>>asList(com.petpace.db.jooq.Keys.KEY_BUSINESS_UNIT_ADMINISTRATORS_PRIMARY, com.petpace.db.jooq.Keys.KEY_BUSINESS_UNIT_ADMINISTRATORS_UNIQ_A581ECB39B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.BusinessUnitAdministratorsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_A581ECB3A58ECB40, com.petpace.db.jooq.Keys.FK_A581ECB39B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.BusinessUnitAdministrators as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.BusinessUnitAdministrators(alias);
	}
}
