/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessAdministrators extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord> {

	private static final long serialVersionUID = 2014895780;

	/**
	 * The singleton instance of <code>sirius.business_administrators</code>
	 */
	public static final com.petpace.db.jooq.tables.BusinessAdministrators BUSINESS_ADMINISTRATORS = new com.petpace.db.jooq.tables.BusinessAdministrators();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord.class;
	}

	/**
	 * The column <code>sirius.business_administrators.business_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord, java.lang.Integer> BUSINESS_ID = createField("business_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.business_administrators.account_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sirius.business_administrators</code> table reference
	 */
	public BusinessAdministrators() {
		super("business_administrators", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.business_administrators</code> table reference
	 */
	public BusinessAdministrators(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.BusinessAdministrators.BUSINESS_ADMINISTRATORS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_BUSINESS_ADMINISTRATORS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord>>asList(com.petpace.db.jooq.Keys.KEY_BUSINESS_ADMINISTRATORS_PRIMARY, com.petpace.db.jooq.Keys.KEY_BUSINESS_ADMINISTRATORS_UNIQ_8D0D93499B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.BusinessAdministratorsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_8D0D9349A89DB457, com.petpace.db.jooq.Keys.FK_8D0D93499B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.BusinessAdministrators as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.BusinessAdministrators(alias);
	}
}
