/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarConfigs extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.CollarConfigsRecord> {

	private static final long serialVersionUID = 655870787;

	/**
	 * The singleton instance of <code>sirius.collar_configs</code>
	 */
	public static final com.petpace.db.jooq.tables.CollarConfigs COLLAR_CONFIGS = new com.petpace.db.jooq.tables.CollarConfigs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.CollarConfigsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.CollarConfigsRecord.class;
	}

	/**
	 * The column <code>sirius.collar_configs.ConfigID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.lang.Integer> CONFIGID = createField("ConfigID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.collar_configs.version</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.collar_configs.Comment</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.lang.String> COMMENT = createField("Comment", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>sirius.collar_configs.s3</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.lang.String> S3 = createField("s3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.collar_configs.uploadDate</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.sql.Timestamp> UPLOADDATE = createField("uploadDate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.collar_configs</code> table reference
	 */
	public CollarConfigs() {
		super("collar_configs", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.collar_configs</code> table reference
	 */
	public CollarConfigs(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.CollarConfigs.COLLAR_CONFIGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.CollarConfigsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_COLLAR_CONFIGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarConfigsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_COLLAR_CONFIGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarConfigsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarConfigsRecord>>asList(com.petpace.db.jooq.Keys.KEY_COLLAR_CONFIGS_PRIMARY, com.petpace.db.jooq.Keys.KEY_COLLAR_CONFIGS_UNIQ_CC613B12BF1CD3C3);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.CollarConfigs as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.CollarConfigs(alias);
	}
}
