/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CollarGroups extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.CollarGroupsRecord> {

	private static final long serialVersionUID = -2005972711;

	/**
	 * The singleton instance of <code>rigel.collar_groups</code>
	 */
	public static final com.petpace.db.jooq.tables.CollarGroups COLLAR_GROUPS = new com.petpace.db.jooq.tables.CollarGroups();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.CollarGroupsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.CollarGroupsRecord.class;
	}

	/**
	 * The column <code>rigel.collar_groups.GroupID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.Integer> GROUPID = createField("GroupID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.collar_groups.name</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.collar_groups.Comment</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.String> COMMENT = createField("Comment", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>rigel.collar_groups.FirmwareID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.Integer> FIRMWAREID = createField("FirmwareID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.collar_groups.ConfigID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.Integer> CONFIGID = createField("ConfigID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.collar_groups</code> table reference
	 */
	public CollarGroups() {
		super("collar_groups", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.collar_groups</code> table reference
	 */
	public CollarGroups(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.CollarGroups.COLLAR_GROUPS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.CollarGroupsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_COLLAR_GROUPS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarGroupsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_COLLAR_GROUPS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarGroupsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.CollarGroupsRecord>>asList(com.petpace.db.jooq.Keys.KEY_COLLAR_GROUPS_PRIMARY, com.petpace.db.jooq.Keys.KEY_COLLAR_GROUPS_UNIQ_46C1E1ED5E237E06);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.CollarGroupsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.CollarGroupsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_46C1E1EDE9AFE03B, com.petpace.db.jooq.Keys.FK_46C1E1EDC0FEDE45);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.CollarGroups as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.CollarGroups(alias);
	}
}
