/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gateways extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.GatewaysRecord> {

	private static final long serialVersionUID = -925161836;

	/**
	 * The singleton instance of <code>sirius.gateways</code>
	 */
	public static final com.petpace.db.jooq.tables.Gateways GATEWAYS = new com.petpace.db.jooq.tables.Gateways();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.GatewaysRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.GatewaysRecord.class;
	}

	/**
	 * The column <code>sirius.gateways.GatewayID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.Integer> GATEWAYID = createField("GatewayID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.gateways.UUID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> UUID = createField("UUID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.HWVersion</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> HWVERSION = createField("HWVersion", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.CurrFWVersion</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> CURRFWVERSION = createField("CurrFWVersion", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.CurrConfVersion</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> CURRCONFVERSION = createField("CurrConfVersion", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.FWProtected</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.Short> FWPROTECTED = createField("FWProtected", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>sirius.gateways.WantSupport</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.Short> WANTSUPPORT = createField("WantSupport", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>sirius.gateways.version</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.Channel</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> CHANNEL = createField("Channel", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.Cookie</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.String> COOKIE = createField("Cookie", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateways.updated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.gateways.GroupID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.Integer> GROUPID = createField("GroupID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sirius.gateways</code> table reference
	 */
	public Gateways() {
		super("gateways", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.gateways</code> table reference
	 */
	public Gateways(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.Gateways.GATEWAYS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.GatewaysRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_GATEWAYS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewaysRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_GATEWAYS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewaysRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewaysRecord>>asList(com.petpace.db.jooq.Keys.KEY_GATEWAYS_PRIMARY, com.petpace.db.jooq.Keys.KEY_GATEWAYS_UNIQ_DBA05D7BE7EABD12);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.GatewaysRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.GatewaysRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_DBA05D7B195291E4);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.Gateways as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.Gateways(alias);
	}
}
