/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayServers extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.GatewayServersRecord> {

	private static final long serialVersionUID = 949664733;

	/**
	 * The singleton instance of <code>rigel.gateway_servers</code>
	 */
	public static final com.petpace.db.jooq.tables.GatewayServers GATEWAY_SERVERS = new com.petpace.db.jooq.tables.GatewayServers();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.GatewayServersRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.GatewayServersRecord.class;
	}

	/**
	 * The column <code>rigel.gateway_servers.ServerID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.lang.Integer> SERVERID = createField("ServerID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.gateway_servers.name</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_servers.HostAddr</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.lang.String> HOSTADDR = createField("HostAddr", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_servers.version</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.lang.String> VERSION = createField("version", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_servers.updated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.sql.Timestamp> UPDATED = createField("updated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>rigel.gateway_servers</code> table reference
	 */
	public GatewayServers() {
		super("gateway_servers", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.gateway_servers</code> table reference
	 */
	public GatewayServers(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.GatewayServers.GATEWAY_SERVERS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.GatewayServersRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_GATEWAY_SERVERS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayServersRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_GATEWAY_SERVERS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayServersRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayServersRecord>>asList(com.petpace.db.jooq.Keys.KEY_GATEWAY_SERVERS_PRIMARY, com.petpace.db.jooq.Keys.KEY_GATEWAY_SERVERS_UNIQ_3E5EBC185E237E06);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.GatewayServers as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.GatewayServers(alias);
	}
}
