/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayFirmwares extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord> {

	private static final long serialVersionUID = -1463851084;

	/**
	 * The singleton instance of <code>sirius.gateway_firmwares</code>
	 */
	public static final com.petpace.db.jooq.tables.GatewayFirmwares GATEWAY_FIRMWARES = new com.petpace.db.jooq.tables.GatewayFirmwares();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord.class;
	}

	/**
	 * The column <code>sirius.gateway_firmwares.FirmwareID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.lang.Integer> FIRMWAREID = createField("FirmwareID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.gateway_firmwares.Version</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.lang.String> VERSION = createField("Version", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateway_firmwares.Comment</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.lang.String> COMMENT = createField("Comment", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>sirius.gateway_firmwares.S3</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.lang.String> S3 = createField("S3", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.gateway_firmwares.UploadDate</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.sql.Timestamp> UPLOADDATE = createField("UploadDate", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.gateway_firmwares</code> table reference
	 */
	public GatewayFirmwares() {
		super("gateway_firmwares", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.gateway_firmwares</code> table reference
	 */
	public GatewayFirmwares(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.GatewayFirmwares.GATEWAY_FIRMWARES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_GATEWAY_FIRMWARES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_GATEWAY_FIRMWARES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayFirmwaresRecord>>asList(com.petpace.db.jooq.Keys.KEY_GATEWAY_FIRMWARES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.GatewayFirmwares as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.GatewayFirmwares(alias);
	}
}
