/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayLogs extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.GatewayLogsRecord> {

	private static final long serialVersionUID = 296447254;

	/**
	 * The singleton instance of <code>rigel.gateway_logs</code>
	 */
	public static final com.petpace.db.jooq.tables.GatewayLogs GATEWAY_LOGS = new com.petpace.db.jooq.tables.GatewayLogs();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.GatewayLogsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.GatewayLogsRecord.class;
	}

	/**
	 * The column <code>rigel.gateway_logs.LogID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.Integer> LOGID = createField("LogID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.gateway_logs.DeviceType</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.String> DEVICETYPE = createField("DeviceType", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_logs.DeviceId</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.String> DEVICEID = createField("DeviceId", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_logs.Severity</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.String> SEVERITY = createField("Severity", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_logs.Message</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.String> MESSAGE = createField("Message", org.jooq.impl.SQLDataType.CLOB.length(65535), this);

	/**
	 * The column <code>rigel.gateway_logs.logTime</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.sql.Timestamp> LOGTIME = createField("logTime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>rigel.gateway_logs</code> table reference
	 */
	public GatewayLogs() {
		super("gateway_logs", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.gateway_logs</code> table reference
	 */
	public GatewayLogs(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.GatewayLogs.GATEWAY_LOGS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.GatewayLogsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_GATEWAY_LOGS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayLogsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_GATEWAY_LOGS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayLogsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayLogsRecord>>asList(com.petpace.db.jooq.Keys.KEY_GATEWAY_LOGS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.GatewayLogs as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.GatewayLogs(alias);
	}
}
