/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GatewayCollarConnections extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord> {

	private static final long serialVersionUID = -1163773782;

	/**
	 * The singleton instance of <code>rigel.gateway_collar_connections</code>
	 */
	public static final com.petpace.db.jooq.tables.GatewayCollarConnections GATEWAY_COLLAR_CONNECTIONS = new com.petpace.db.jooq.tables.GatewayCollarConnections();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord.class;
	}

	/**
	 * The column <code>rigel.gateway_collar_connections.isActive</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, java.lang.Short> ISACTIVE = createField("isActive", org.jooq.impl.SQLDataType.SMALLINT, this);

	/**
	 * The column <code>rigel.gateway_collar_connections.connectTime</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, java.sql.Timestamp> CONNECTTIME = createField("connectTime", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.gateway_collar_connections.GollarID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, java.lang.String> GOLLARID = createField("GollarID", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.gateway_collar_connections.GatewayID</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, java.lang.Integer> GATEWAYID = createField("GatewayID", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.gateway_collar_connections</code> table reference
	 */
	public GatewayCollarConnections() {
		super("gateway_collar_connections", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.gateway_collar_connections</code> table reference
	 */
	public GatewayCollarConnections(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.GatewayCollarConnections.GATEWAY_COLLAR_CONNECTIONS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_GATEWAY_COLLAR_CONNECTIONS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord>>asList(com.petpace.db.jooq.Keys.KEY_GATEWAY_COLLAR_CONNECTIONS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.GatewayCollarConnectionsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_E80ED9C89C952061, com.petpace.db.jooq.Keys.FK_E80ED9C8C3E73E37);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.GatewayCollarConnections as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.GatewayCollarConnections(alias);
	}
}
