/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAttributes extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.PetAttributesRecord> {

	private static final long serialVersionUID = 1199368131;

	/**
	 * The singleton instance of <code>rigel.pet_attributes</code>
	 */
	public static final com.petpace.db.jooq.tables.PetAttributes PET_ATTRIBUTES = new com.petpace.db.jooq.tables.PetAttributes();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.PetAttributesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.PetAttributesRecord.class;
	}

	/**
	 * The column <code>rigel.pet_attributes.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.pet_attributes.name</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.pet_attributes.dataType</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.String> DATATYPE = createField("dataType", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.pet_attributes.defaultValue</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.String> DEFAULTVALUE = createField("defaultValue", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>rigel.pet_attributes.isRequired</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.Integer> ISREQUIRED = createField("isRequired", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>rigel.pet_attributes.dateCreated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.sql.Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.pet_attributes.dateUpdated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.sql.Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.pet_attributes.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.pet_attributes</code> table reference
	 */
	public PetAttributes() {
		super("pet_attributes", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.pet_attributes</code> table reference
	 */
	public PetAttributes(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.PetAttributes.PET_ATTRIBUTES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.PetAttributesRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_PET_ATTRIBUTES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetAttributesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_PET_ATTRIBUTES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetAttributesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetAttributesRecord>>asList(com.petpace.db.jooq.Keys.KEY_PET_ATTRIBUTES_PRIMARY, com.petpace.db.jooq.Keys.KEY_PET_ATTRIBUTES_UNIQ_3613C6A05E237E06);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.PetAttributes as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.PetAttributes(alias);
	}
}
