/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetEntities extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.PetEntitiesRecord> {

	private static final long serialVersionUID = 1231346950;

	/**
	 * The singleton instance of <code>rigel.pet_entities</code>
	 */
	public static final com.petpace.db.jooq.tables.PetEntities PET_ENTITIES = new com.petpace.db.jooq.tables.PetEntities();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.PetEntitiesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.PetEntitiesRecord.class;
	}

	/**
	 * The column <code>rigel.pet_entities.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetEntitiesRecord, java.lang.String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>rigel.pet_entities.dateCreated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetEntitiesRecord, java.sql.Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.pet_entities.dateUpdated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetEntitiesRecord, java.sql.Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>rigel.pet_entities.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetEntitiesRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>rigel.pet_entities</code> table reference
	 */
	public PetEntities() {
		super("pet_entities", com.petpace.db.jooq.Rigel.RIGEL);
	}

	/**
	 * Create an aliased <code>rigel.pet_entities</code> table reference
	 */
	public PetEntities(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Rigel.RIGEL, com.petpace.db.jooq.tables.PetEntities.PET_ENTITIES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetEntitiesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_PET_ENTITIES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetEntitiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetEntitiesRecord>>asList(com.petpace.db.jooq.Keys.KEY_PET_ENTITIES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.PetEntities as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.PetEntities(alias);
	}
}
