/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetPrimaryVeterinarians extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord> {

	private static final long serialVersionUID = 1759904415;

	/**
	 * The singleton instance of <code>sirius.pet_primary_veterinarians</code>
	 */
	public static final com.petpace.db.jooq.tables.PetPrimaryVeterinarians PET_PRIMARY_VETERINARIANS = new com.petpace.db.jooq.tables.PetPrimaryVeterinarians();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord.class;
	}

	/**
	 * The column <code>sirius.pet_primary_veterinarians.vet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.lang.Integer> VET_ID = createField("vet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.pet_primary_veterinarians.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.pet_primary_veterinarians.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.pet_primary_veterinarians.start</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.sql.Timestamp> START = createField("start", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.pet_primary_veterinarians.end</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.sql.Timestamp> END = createField("end", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.pet_primary_veterinarians.notes</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, java.lang.String> NOTES = createField("notes", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>sirius.pet_primary_veterinarians</code> table reference
	 */
	public PetPrimaryVeterinarians() {
		super("pet_primary_veterinarians", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.pet_primary_veterinarians</code> table reference
	 */
	public PetPrimaryVeterinarians(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.PetPrimaryVeterinarians.PET_PRIMARY_VETERINARIANS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_PET_PRIMARY_VETERINARIANS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord>>asList(com.petpace.db.jooq.Keys.KEY_PET_PRIMARY_VETERINARIANS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.PetPrimaryVeterinariansRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_76D48E6840369CAB, com.petpace.db.jooq.Keys.FK_76D48E68966F7FB6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.PetPrimaryVeterinarians as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.PetPrimaryVeterinarians(alias);
	}
}
