/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RemoteLogins extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.RemoteLoginsRecord> {

	private static final long serialVersionUID = 427123566;

	/**
	 * The singleton instance of <code>sirius.remote_logins</code>
	 */
	public static final com.petpace.db.jooq.tables.RemoteLogins REMOTE_LOGINS = new com.petpace.db.jooq.tables.RemoteLogins();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.RemoteLoginsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.RemoteLoginsRecord.class;
	}

	/**
	 * The column <code>sirius.remote_logins.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.remote_logins.collar_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.String> COLLAR_ID = createField("collar_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.remote_logins.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.remote_logins.account_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.remote_logins.start</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.sql.Timestamp> START = createField("start", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.remote_logins.end</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.sql.Timestamp> END = createField("end", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.remote_logins.microtime</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Double> MICROTIME = createField("microtime", org.jooq.impl.SQLDataType.DOUBLE, this);

	/**
	 * The column <code>sirius.remote_logins.samplingFrequency</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.String> SAMPLINGFREQUENCY = createField("samplingFrequency", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.remote_logins.duration</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> DURATION = createField("duration", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.remote_logins.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.remote_logins.notes</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.String> NOTES = createField("notes", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * Create a <code>sirius.remote_logins</code> table reference
	 */
	public RemoteLogins() {
		super("remote_logins", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.remote_logins</code> table reference
	 */
	public RemoteLogins(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.RemoteLogins.REMOTE_LOGINS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_REMOTE_LOGINS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RemoteLoginsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_REMOTE_LOGINS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RemoteLoginsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RemoteLoginsRecord>>asList(com.petpace.db.jooq.Keys.KEY_REMOTE_LOGINS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.RemoteLoginsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_8989C3C84568D8A0, com.petpace.db.jooq.Keys.FK_8989C3C8966F7FB6, com.petpace.db.jooq.Keys.FK_8989C3C89B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.RemoteLogins as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.RemoteLogins(alias);
	}
}
