/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Roles extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.RolesRecord> {

	private static final long serialVersionUID = 1245429645;

	/**
	 * The singleton instance of <code>sirius.roles</code>
	 */
	public static final com.petpace.db.jooq.tables.Roles ROLES = new com.petpace.db.jooq.tables.Roles();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.RolesRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.RolesRecord.class;
	}

	/**
	 * The column <code>sirius.roles.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.roles.account_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.roles.name</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.lang.String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.roles.dateCreated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.sql.Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.roles.dateUpdated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.sql.Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.roles.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.RolesRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sirius.roles</code> table reference
	 */
	public Roles() {
		super("roles", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.roles</code> table reference
	 */
	public Roles(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.Roles.ROLES);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.RolesRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_ROLES;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RolesRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_ROLES_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RolesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.RolesRecord>>asList(com.petpace.db.jooq.Keys.KEY_ROLES_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.RolesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.RolesRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_B63E2EC79B6B5FBA);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.Roles as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.Roles(alias);
	}
}
