/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Veterinarians extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.VeterinariansRecord> {

	private static final long serialVersionUID = -1157559010;

	/**
	 * The singleton instance of <code>sirius.veterinarians</code>
	 */
	public static final com.petpace.db.jooq.tables.Veterinarians VETERINARIANS = new com.petpace.db.jooq.tables.Veterinarians();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.VeterinariansRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.VeterinariansRecord.class;
	}

	/**
	 * The column <code>sirius.veterinarians.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.veterinarians.account_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.veterinarians.address_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.veterinarians.fullName</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> FULLNAME = createField("fullName", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.clinic</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> CLINIC = createField("clinic", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.prefix</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> PREFIX = createField("prefix", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.suffix</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> SUFFIX = createField("suffix", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.phone</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.cell</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> CELL = createField("cell", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.fax</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> FAX = createField("fax", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.hours</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> HOURS = createField("hours", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.veterinarians.dateCreated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.sql.Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.veterinarians.dateUpdated</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.sql.Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.veterinarians.status</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> STATUS = createField("status", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.veterinarians.about</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.String> ABOUT = createField("about", org.jooq.impl.SQLDataType.CLOB, this);

	/**
	 * The column <code>sirius.veterinarians.primary_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> PRIMARY_ID = createField("primary_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * Create a <code>sirius.veterinarians</code> table reference
	 */
	public Veterinarians() {
		super("veterinarians", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.veterinarians</code> table reference
	 */
	public Veterinarians(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.Veterinarians.VETERINARIANS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.VeterinariansRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_VETERINARIANS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VeterinariansRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_VETERINARIANS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VeterinariansRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VeterinariansRecord>>asList(com.petpace.db.jooq.Keys.KEY_VETERINARIANS_PRIMARY, com.petpace.db.jooq.Keys.KEY_VETERINARIANS_UNIQ_6B2A679C9B6B5FBA, com.petpace.db.jooq.Keys.KEY_VETERINARIANS_UNIQ_6B2A679CF5B7AF75);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VeterinariansRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VeterinariansRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_6B2A679C9B6B5FBA, com.petpace.db.jooq.Keys.FK_6B2A679CF5B7AF75, com.petpace.db.jooq.Keys.FK_6B2A679C21DE0C6C);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.Veterinarians as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.Veterinarians(alias);
	}
}
