/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalActivityHour extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.VitalActivityHourRecord> {

	private static final long serialVersionUID = 1879075320;

	/**
	 * The singleton instance of <code>sirius.vital_activity_hour</code>
	 */
	public static final com.petpace.db.jooq.tables.VitalActivityHour VITAL_ACTIVITY_HOUR = new com.petpace.db.jooq.tables.VitalActivityHour();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.VitalActivityHourRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.VitalActivityHourRecord.class;
	}

	/**
	 * The column <code>sirius.vital_activity_hour.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vital_activity_hour.collar_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.lang.String> COLLAR_ID = createField("collar_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.vital_activity_hour.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vital_activity_hour.value</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.lang.Long> VALUE = createField("value", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vital_activity_hour.smv10</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.math.BigDecimal> SMV10 = createField("smv10", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_activity_hour.smv30</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.math.BigDecimal> SMV30 = createField("smv30", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_activity_hour.time</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.sql.Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.vital_activity_hour</code> table reference
	 */
	public VitalActivityHour() {
		super("vital_activity_hour", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.vital_activity_hour</code> table reference
	 */
	public VitalActivityHour(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.VitalActivityHour.VITAL_ACTIVITY_HOUR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_VITAL_ACTIVITY_HOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalActivityHourRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_VITAL_ACTIVITY_HOUR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalActivityHourRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalActivityHourRecord>>asList(com.petpace.db.jooq.Keys.KEY_VITAL_ACTIVITY_HOUR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalActivityHourRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_AABD596F4568D8A0, com.petpace.db.jooq.Keys.FK_AABD596F966F7FB6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.VitalActivityHour as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.VitalActivityHour(alias);
	}
}
