/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VitalBodytempHour extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord> {

	private static final long serialVersionUID = -921653582;

	/**
	 * The singleton instance of <code>sirius.vital_bodytemp_hour</code>
	 */
	public static final com.petpace.db.jooq.tables.VitalBodytempHour VITAL_BODYTEMP_HOUR = new com.petpace.db.jooq.tables.VitalBodytempHour();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.VitalBodytempHourRecord.class;
	}

	/**
	 * The column <code>sirius.vital_bodytemp_hour.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.collar_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.lang.String> COLLAR_ID = createField("collar_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.value</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.lang.Long> VALUE = createField("value", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.ambient</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.math.BigDecimal> AMBIENT = createField("ambient", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.hiLimit</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.math.BigDecimal> HILIMIT = createField("hiLimit", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.lowLimit</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.math.BigDecimal> LOWLIMIT = createField("lowLimit", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.smv10</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.math.BigDecimal> SMV10 = createField("smv10", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.smv30</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.math.BigDecimal> SMV30 = createField("smv30", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vital_bodytemp_hour.time</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.sql.Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.vital_bodytemp_hour</code> table reference
	 */
	public VitalBodytempHour() {
		super("vital_bodytemp_hour", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.vital_bodytemp_hour</code> table reference
	 */
	public VitalBodytempHour(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.VitalBodytempHour.VITAL_BODYTEMP_HOUR);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_VITAL_BODYTEMP_HOUR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_VITAL_BODYTEMP_HOUR_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord>>asList(com.petpace.db.jooq.Keys.KEY_VITAL_BODYTEMP_HOUR_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalBodytempHourRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_B5C40ABC4568D8A0, com.petpace.db.jooq.Keys.FK_B5C40ABC966F7FB6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.VitalBodytempHour as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.VitalBodytempHour(alias);
	}
}
