/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vitals extends org.jooq.impl.TableImpl<com.petpace.db.jooq.tables.records.VitalsRecord> {

	private static final long serialVersionUID = -559356543;

	/**
	 * The singleton instance of <code>sirius.vitals</code>
	 */
	public static final com.petpace.db.jooq.tables.Vitals VITALS = new com.petpace.db.jooq.tables.Vitals();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.petpace.db.jooq.tables.records.VitalsRecord> getRecordType() {
		return com.petpace.db.jooq.tables.records.VitalsRecord.class;
	}

	/**
	 * The column <code>sirius.vitals.id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vitals.collar_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.String> COLLAR_ID = createField("collar_id", org.jooq.impl.SQLDataType.VARCHAR.length(255), this);

	/**
	 * The column <code>sirius.vitals.pet_id</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Integer> PET_ID = createField("pet_id", org.jooq.impl.SQLDataType.INTEGER, this);

	/**
	 * The column <code>sirius.vitals.ambientTemp</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.math.BigDecimal> AMBIENTTEMP = createField("ambientTemp", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vitals.bodyTemp</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.math.BigDecimal> BODYTEMP = createField("bodyTemp", org.jooq.impl.SQLDataType.DECIMAL.precision(10, 2), this);

	/**
	 * The column <code>sirius.vitals.pulse</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Long> PULSE = createField("pulse", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vitals.respiratory</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Long> RESPIRATORY = createField("respiratory", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vitals.activity</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Long> ACTIVITY = createField("activity", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vitals.position</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Long> POSITION = createField("position", org.jooq.impl.SQLDataType.BIGINT, this);

	/**
	 * The column <code>sirius.vitals.time</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.sql.Timestamp> TIME = createField("time", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * The column <code>sirius.vitals.created</code>. 
	 */
	public final org.jooq.TableField<com.petpace.db.jooq.tables.records.VitalsRecord, java.sql.Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP, this);

	/**
	 * Create a <code>sirius.vitals</code> table reference
	 */
	public Vitals() {
		super("vitals", com.petpace.db.jooq.Sirius.SIRIUS);
	}

	/**
	 * Create an aliased <code>sirius.vitals</code> table reference
	 */
	public Vitals(java.lang.String alias) {
		super(alias, com.petpace.db.jooq.Sirius.SIRIUS, com.petpace.db.jooq.tables.Vitals.VITALS);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.petpace.db.jooq.tables.records.VitalsRecord, java.lang.Integer> getIdentity() {
		return com.petpace.db.jooq.Keys.IDENTITY_VITALS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalsRecord> getPrimaryKey() {
		return com.petpace.db.jooq.Keys.KEY_VITALS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.petpace.db.jooq.tables.records.VitalsRecord>>asList(com.petpace.db.jooq.Keys.KEY_VITALS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.petpace.db.jooq.tables.records.VitalsRecord, ?>>asList(com.petpace.db.jooq.Keys.FK_5597C8B24568D8A0, com.petpace.db.jooq.Keys.FK_5597C8B2966F7FB6);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.petpace.db.jooq.tables.Vitals as(java.lang.String alias) {
		return new com.petpace.db.jooq.tables.Vitals(alias);
	}
}
