/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationPreferenceOwners implements java.io.Serializable {

	private static final long serialVersionUID = 1625808642;

	private java.lang.Integer accountId;
	private java.lang.Integer preferenceId;

	public java.lang.Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(java.lang.Integer accountId) {
		this.accountId = accountId;
	}

	public java.lang.Integer getPreferenceId() {
		return this.preferenceId;
	}

	public void setPreferenceId(java.lang.Integer preferenceId) {
		this.preferenceId = preferenceId;
	}
}
