/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationReceivers implements java.io.Serializable {

	private static final long serialVersionUID = 1708279920;

	private java.lang.Integer id;
	private java.lang.String  protocol;
	private java.lang.String  address;
	private java.lang.String  message;
	private java.lang.Integer confirmationrequired;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getProtocol() {
		return this.protocol;
	}

	public void setProtocol(java.lang.String protocol) {
		this.protocol = protocol;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.Integer getConfirmationrequired() {
		return this.confirmationrequired;
	}

	public void setConfirmationrequired(java.lang.Integer confirmationrequired) {
		this.confirmationrequired = confirmationrequired;
	}
}
