/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotifications implements java.io.Serializable {

	private static final long serialVersionUID = 67921974;

	private java.lang.Integer  id;
	private java.lang.Integer  alertId;
	private java.lang.Integer  confirmationrequired;
	private java.sql.Timestamp created;
	private java.lang.Integer  status;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAlertId() {
		return this.alertId;
	}

	public void setAlertId(java.lang.Integer alertId) {
		this.alertId = alertId;
	}

	public java.lang.Integer getConfirmationrequired() {
		return this.confirmationrequired;
	}

	public void setConfirmationrequired(java.lang.Integer confirmationrequired) {
		this.confirmationrequired = confirmationrequired;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}
}
