/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationPreferences implements java.io.Serializable {

	private static final long serialVersionUID = -1603335349;

	private java.lang.Integer  id;
	private java.lang.String   phonelist;
	private java.lang.String   emaillist;
	private java.lang.String   smslist;
	private java.sql.Timestamp created;
	private java.sql.Timestamp updated;
	private java.lang.Integer  status;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getPhonelist() {
		return this.phonelist;
	}

	public void setPhonelist(java.lang.String phonelist) {
		this.phonelist = phonelist;
	}

	public java.lang.String getEmaillist() {
		return this.emaillist;
	}

	public void setEmaillist(java.lang.String emaillist) {
		this.emaillist = emaillist;
	}

	public java.lang.String getSmslist() {
		return this.smslist;
	}

	public void setSmslist(java.lang.String smslist) {
		this.smslist = smslist;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.sql.Timestamp getUpdated() {
		return this.updated;
	}

	public void setUpdated(java.sql.Timestamp updated) {
		this.updated = updated;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}
}
