/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlertNotificationPreferencePets implements java.io.Serializable {

	private static final long serialVersionUID = -1717085473;

	private java.lang.Integer petId;
	private java.lang.Integer preferenceId;
	private java.lang.Integer businessunitId;

	public java.lang.Integer getPetId() {
		return this.petId;
	}

	public void setPetId(java.lang.Integer petId) {
		this.petId = petId;
	}

	public java.lang.Integer getPreferenceId() {
		return this.preferenceId;
	}

	public void setPreferenceId(java.lang.Integer preferenceId) {
		this.preferenceId = preferenceId;
	}

	public java.lang.Integer getBusinessunitId() {
		return this.businessunitId;
	}

	public void setBusinessunitId(java.lang.Integer businessunitId) {
		this.businessunitId = businessunitId;
	}
}
