/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedAttributes implements java.io.Serializable {

	private static final long serialVersionUID = 1680217236;

	private java.lang.String id;
	private java.lang.String datatype;

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public java.lang.String getDatatype() {
		return this.datatype;
	}

	public void setDatatype(java.lang.String datatype) {
		this.datatype = datatype;
	}
}
