/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedAttributeValuesVarchar implements java.io.Serializable {

	private static final long serialVersionUID = 1018948820;

	private java.lang.Integer id;
	private java.lang.String  breedId;
	private java.lang.String  val;
	private java.lang.String  breedattributeId;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getBreedId() {
		return this.breedId;
	}

	public void setBreedId(java.lang.String breedId) {
		this.breedId = breedId;
	}

	public java.lang.String getVal() {
		return this.val;
	}

	public void setVal(java.lang.String val) {
		this.val = val;
	}

	public java.lang.String getBreedattributeId() {
		return this.breedattributeId;
	}

	public void setBreedattributeId(java.lang.String breedattributeId) {
		this.breedattributeId = breedattributeId;
	}
}
