/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BreedAttributeGrouping implements java.io.Serializable {

	private static final long serialVersionUID = -935168633;

	private java.lang.String  attributeId;
	private java.lang.Integer groupId;

	public java.lang.String getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(java.lang.String attributeId) {
		this.attributeId = attributeId;
	}

	public java.lang.Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.Integer groupId) {
		this.groupId = groupId;
	}
}
