/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessAdministrators implements java.io.Serializable {

	private static final long serialVersionUID = 1956957015;

	private java.lang.Integer businessId;
	private java.lang.Integer accountId;

	public java.lang.Integer getBusinessId() {
		return this.businessId;
	}

	public void setBusinessId(java.lang.Integer businessId) {
		this.businessId = businessId;
	}

	public java.lang.Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(java.lang.Integer accountId) {
		this.accountId = accountId;
	}
}
