/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Businesses implements java.io.Serializable {

	private static final long serialVersionUID = 327363001;

	private java.lang.Integer  id;
	private java.lang.Integer  addressId;
	private java.lang.String   name;
	private java.lang.String   url;
	private java.lang.Integer  btype;
	private java.lang.String   website;
	private java.lang.String   phone;
	private java.lang.String   fax;
	private java.sql.Timestamp created;
	private java.sql.Timestamp updated;
	private java.lang.Integer  status;
	private java.lang.Integer  parentId;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(java.lang.Integer addressId) {
		this.addressId = addressId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.Integer getBtype() {
		return this.btype;
	}

	public void setBtype(java.lang.Integer btype) {
		this.btype = btype;
	}

	public java.lang.String getWebsite() {
		return this.website;
	}

	public void setWebsite(java.lang.String website) {
		this.website = website;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getFax() {
		return this.fax;
	}

	public void setFax(java.lang.String fax) {
		this.fax = fax;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.sql.Timestamp getUpdated() {
		return this.updated;
	}

	public void setUpdated(java.sql.Timestamp updated) {
		this.updated = updated;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(java.lang.Integer parentId) {
		this.parentId = parentId;
	}
}
