/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BusinessUnitCollars implements java.io.Serializable {

	private static final long serialVersionUID = 448430732;

	private java.lang.Integer businessUnitId;
	private java.lang.String  collarId;

	public java.lang.Integer getBusinessUnitId() {
		return this.businessUnitId;
	}

	public void setBusinessUnitId(java.lang.Integer businessUnitId) {
		this.businessUnitId = businessUnitId;
	}

	public java.lang.String getCollarId() {
		return this.collarId;
	}

	public void setCollarId(java.lang.String collarId) {
		this.collarId = collarId;
	}
}
