/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Gateways implements java.io.Serializable {

	private static final long serialVersionUID = 551063336;

	private java.lang.Integer  gatewayid;
	private java.lang.String   uuid;
	private java.lang.String   hwversion;
	private java.lang.String   currfwversion;
	private java.lang.String   currconfversion;
	private java.lang.Short    fwprotected;
	private java.lang.Short    wantsupport;
	private java.lang.String   version;
	private java.lang.String   channel;
	private java.lang.String   cookie;
	private java.sql.Timestamp updated;
	private java.lang.Integer  groupid;

	public java.lang.Integer getGatewayid() {
		return this.gatewayid;
	}

	public void setGatewayid(java.lang.Integer gatewayid) {
		this.gatewayid = gatewayid;
	}

	public java.lang.String getUuid() {
		return this.uuid;
	}

	public void setUuid(java.lang.String uuid) {
		this.uuid = uuid;
	}

	public java.lang.String getHwversion() {
		return this.hwversion;
	}

	public void setHwversion(java.lang.String hwversion) {
		this.hwversion = hwversion;
	}

	public java.lang.String getCurrfwversion() {
		return this.currfwversion;
	}

	public void setCurrfwversion(java.lang.String currfwversion) {
		this.currfwversion = currfwversion;
	}

	public java.lang.String getCurrconfversion() {
		return this.currconfversion;
	}

	public void setCurrconfversion(java.lang.String currconfversion) {
		this.currconfversion = currconfversion;
	}

	public java.lang.Short getFwprotected() {
		return this.fwprotected;
	}

	public void setFwprotected(java.lang.Short fwprotected) {
		this.fwprotected = fwprotected;
	}

	public java.lang.Short getWantsupport() {
		return this.wantsupport;
	}

	public void setWantsupport(java.lang.Short wantsupport) {
		this.wantsupport = wantsupport;
	}

	public java.lang.String getVersion() {
		return this.version;
	}

	public void setVersion(java.lang.String version) {
		this.version = version;
	}

	public java.lang.String getChannel() {
		return this.channel;
	}

	public void setChannel(java.lang.String channel) {
		this.channel = channel;
	}

	public java.lang.String getCookie() {
		return this.cookie;
	}

	public void setCookie(java.lang.String cookie) {
		this.cookie = cookie;
	}

	public java.sql.Timestamp getUpdated() {
		return this.updated;
	}

	public void setUpdated(java.sql.Timestamp updated) {
		this.updated = updated;
	}

	public java.lang.Integer getGroupid() {
		return this.groupid;
	}

	public void setGroupid(java.lang.Integer groupid) {
		this.groupid = groupid;
	}
}
