/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAttributeGroups implements java.io.Serializable {

	private static final long serialVersionUID = 1665979853;

	private java.lang.Integer  id;
	private java.lang.String   entityId;
	private java.lang.String   name;
	private java.sql.Timestamp datecreated;
	private java.sql.Timestamp dateupdated;
	private java.lang.Integer  status;
	private java.lang.String   note;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(java.lang.String entityId) {
		this.entityId = entityId;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.sql.Timestamp getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(java.sql.Timestamp datecreated) {
		this.datecreated = datecreated;
	}

	public java.sql.Timestamp getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(java.sql.Timestamp dateupdated) {
		this.dateupdated = dateupdated;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.String getNote() {
		return this.note;
	}

	public void setNote(java.lang.String note) {
		this.note = note;
	}
}
