/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetAttributeGrouping implements java.io.Serializable {

	private static final long serialVersionUID = 30429317;

	private java.lang.Integer groupId;
	private java.lang.Integer attributeId;
	private java.lang.Integer sort;

	public java.lang.Integer getGroupId() {
		return this.groupId;
	}

	public void setGroupId(java.lang.Integer groupId) {
		this.groupId = groupId;
	}

	public java.lang.Integer getAttributeId() {
		return this.attributeId;
	}

	public void setAttributeId(java.lang.Integer attributeId) {
		this.attributeId = attributeId;
	}

	public java.lang.Integer getSort() {
		return this.sort;
	}

	public void setSort(java.lang.Integer sort) {
		this.sort = sort;
	}
}
