/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PetPrimaryVeterinarians implements java.io.Serializable {

	private static final long serialVersionUID = 1343620133;

	private java.lang.Integer  vetId;
	private java.lang.Integer  petId;
	private java.lang.Integer  status;
	private java.sql.Timestamp start;
	private java.sql.Timestamp end;
	private java.lang.String   notes;

	public java.lang.Integer getVetId() {
		return this.vetId;
	}

	public void setVetId(java.lang.Integer vetId) {
		this.vetId = vetId;
	}

	public java.lang.Integer getPetId() {
		return this.petId;
	}

	public void setPetId(java.lang.Integer petId) {
		this.petId = petId;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.sql.Timestamp getStart() {
		return this.start;
	}

	public void setStart(java.sql.Timestamp start) {
		this.start = start;
	}

	public java.sql.Timestamp getEnd() {
		return this.end;
	}

	public void setEnd(java.sql.Timestamp end) {
		this.end = end;
	}

	public java.lang.String getNotes() {
		return this.notes;
	}

	public void setNotes(java.lang.String notes) {
		this.notes = notes;
	}
}
