/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlaceNeighborhoods implements java.io.Serializable {

	private static final long serialVersionUID = 1075032808;

	private java.lang.Integer  id;
	private java.lang.String   name;
	private java.lang.String   sub;
	private java.lang.String   display;
	private java.lang.String   url;
	private java.lang.String   city;
	private java.lang.String   region;
	private java.lang.String   country;
	private java.lang.Double   latitude;
	private java.lang.Double   longitude;
	private java.sql.Timestamp created;
	private java.lang.Integer  status;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getSub() {
		return this.sub;
	}

	public void setSub(java.lang.String sub) {
		this.sub = sub;
	}

	public java.lang.String getDisplay() {
		return this.display;
	}

	public void setDisplay(java.lang.String display) {
		this.display = display;
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public java.lang.String getCity() {
		return this.city;
	}

	public void setCity(java.lang.String city) {
		this.city = city;
	}

	public java.lang.String getRegion() {
		return this.region;
	}

	public void setRegion(java.lang.String region) {
		this.region = region;
	}

	public java.lang.String getCountry() {
		return this.country;
	}

	public void setCountry(java.lang.String country) {
		this.country = country;
	}

	public java.lang.Double getLatitude() {
		return this.latitude;
	}

	public void setLatitude(java.lang.Double latitude) {
		this.latitude = latitude;
	}

	public java.lang.Double getLongitude() {
		return this.longitude;
	}

	public void setLongitude(java.lang.Double longitude) {
		this.longitude = longitude;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}
}
