/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Veterinarians implements java.io.Serializable {

	private static final long serialVersionUID = 881293136;

	private java.lang.Integer  id;
	private java.lang.Integer  accountId;
	private java.lang.Integer  addressId;
	private java.lang.String   fullname;
	private java.lang.String   clinic;
	private java.lang.String   prefix;
	private java.lang.String   suffix;
	private java.lang.String   phone;
	private java.lang.String   cell;
	private java.lang.String   fax;
	private java.lang.String   hours;
	private java.sql.Timestamp datecreated;
	private java.sql.Timestamp dateupdated;
	private java.lang.Integer  status;
	private java.lang.String   about;
	private java.lang.Integer  primaryId;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.Integer getAccountId() {
		return this.accountId;
	}

	public void setAccountId(java.lang.Integer accountId) {
		this.accountId = accountId;
	}

	public java.lang.Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(java.lang.Integer addressId) {
		this.addressId = addressId;
	}

	public java.lang.String getFullname() {
		return this.fullname;
	}

	public void setFullname(java.lang.String fullname) {
		this.fullname = fullname;
	}

	public java.lang.String getClinic() {
		return this.clinic;
	}

	public void setClinic(java.lang.String clinic) {
		this.clinic = clinic;
	}

	public java.lang.String getPrefix() {
		return this.prefix;
	}

	public void setPrefix(java.lang.String prefix) {
		this.prefix = prefix;
	}

	public java.lang.String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(java.lang.String suffix) {
		this.suffix = suffix;
	}

	public java.lang.String getPhone() {
		return this.phone;
	}

	public void setPhone(java.lang.String phone) {
		this.phone = phone;
	}

	public java.lang.String getCell() {
		return this.cell;
	}

	public void setCell(java.lang.String cell) {
		this.cell = cell;
	}

	public java.lang.String getFax() {
		return this.fax;
	}

	public void setFax(java.lang.String fax) {
		this.fax = fax;
	}

	public java.lang.String getHours() {
		return this.hours;
	}

	public void setHours(java.lang.String hours) {
		this.hours = hours;
	}

	public java.sql.Timestamp getDatecreated() {
		return this.datecreated;
	}

	public void setDatecreated(java.sql.Timestamp datecreated) {
		this.datecreated = datecreated;
	}

	public java.sql.Timestamp getDateupdated() {
		return this.dateupdated;
	}

	public void setDateupdated(java.sql.Timestamp dateupdated) {
		this.dateupdated = dateupdated;
	}

	public java.lang.Integer getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.Integer status) {
		this.status = status;
	}

	public java.lang.String getAbout() {
		return this.about;
	}

	public void setAbout(java.lang.String about) {
		this.about = about;
	}

	public java.lang.Integer getPrimaryId() {
		return this.primaryId;
	}

	public void setPrimaryId(java.lang.Integer primaryId) {
		this.primaryId = primaryId;
	}
}
