/**
 * This class is generated by jOOQ
 */
package com.petpace.db.jooq.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vitals implements java.io.Serializable {

	private static final long serialVersionUID = 1950785833;

	private java.lang.Integer    id;
	private java.lang.String     collarId;
	private java.lang.Integer    petId;
	private java.math.BigDecimal ambienttemp;
	private java.math.BigDecimal bodytemp;
	private java.lang.Long       pulse;
	private java.lang.Long       respiratory;
	private java.lang.Long       activity;
	private java.lang.Long       position;
	private java.sql.Timestamp   time;
	private java.sql.Timestamp   created;

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public java.lang.String getCollarId() {
		return this.collarId;
	}

	public void setCollarId(java.lang.String collarId) {
		this.collarId = collarId;
	}

	public java.lang.Integer getPetId() {
		return this.petId;
	}

	public void setPetId(java.lang.Integer petId) {
		this.petId = petId;
	}

	public java.math.BigDecimal getAmbienttemp() {
		return this.ambienttemp;
	}

	public void setAmbienttemp(java.math.BigDecimal ambienttemp) {
		this.ambienttemp = ambienttemp;
	}

	public java.math.BigDecimal getBodytemp() {
		return this.bodytemp;
	}

	public void setBodytemp(java.math.BigDecimal bodytemp) {
		this.bodytemp = bodytemp;
	}

	public java.lang.Long getPulse() {
		return this.pulse;
	}

	public void setPulse(java.lang.Long pulse) {
		this.pulse = pulse;
	}

	public java.lang.Long getRespiratory() {
		return this.respiratory;
	}

	public void setRespiratory(java.lang.Long respiratory) {
		this.respiratory = respiratory;
	}

	public java.lang.Long getActivity() {
		return this.activity;
	}

	public void setActivity(java.lang.Long activity) {
		this.activity = activity;
	}

	public java.lang.Long getPosition() {
		return this.position;
	}

	public void setPosition(java.lang.Long position) {
		this.position = position;
	}

	public java.sql.Timestamp getTime() {
		return this.time;
	}

	public void setTime(java.sql.Timestamp time) {
		this.time = time;
	}

	public java.sql.Timestamp getCreated() {
		return this.created;
	}

	public void setCreated(java.sql.Timestamp created) {
		this.created = created;
	}
}
